### ISSUE TITLE
NameError: name 'httpx' is not defined

### ISSUE THREAD

**Issue by kwevers** [python-semantic-release/python-semantic-release#1023]
### Description
Since today's [v4.11.0](https://github.com/python-gitlab/python-gitlab/releases/tag/v4.11.0) release of `python-gitlab` using the semantic release GitHub Actions fails with a `NameError: name 'httpx' is not defined` error.

### Expected behavior

Successful release creation

### Actual behavior

```
Run python-semantic-release/python-semantic-release@v9.8.8
  with:
    github_token: ***
    vcs_release: false
    root_options: -v
    directory: .
  env:
    COMMIT_AUTHOR: Kristof Wevers <kwevers@users.noreply.github.com>
/usr/bin/docker run --name f47b6874051d5822284c479b32b399ba2e846a_550727 --label f47b68 --workdir /github/workspace --rm -e "COMMIT_AUTHOR" -e "INPUT_GITHUB_TOKEN" -e "INPUT_VCS_RELEASE" -e "INPUT_ROOT_OPTIONS" -e "INPUT_DIRECTORY" -e "INPUT_GIT_COMMITTER_NAME" -e "INPUT_GIT_COMMITTER_EMAIL" -e "INPUT_SSH_PUBLIC_SIGNING_KEY" -e "INPUT_SSH_PRIVATE_SIGNING_KEY" -e "INPUT_PRERELEASE" -e "INPUT_PRERELEASE_TOKEN" -e "INPUT_FORCE" -e "INPUT_COMMIT" -e "INPUT_TAG" -e "INPUT_PUSH" -e "INPUT_CHANGELOG" -e "INPUT_BUILD_METADATA" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/tf-aws-cloudwatch/tf-aws-cloudwatch":"/github/workspace" f47b68:74051d5822284c479b32b399ba2e846a
Traceback (most recent call last):
  File "/psr/.venv/bin/semantic-release", line 5, in <module>
    from semantic_release.cli.commands.main import main
  File "/psr/.venv/lib/python3.12/site-packages/semantic_release/cli/commands/main.py", line 13, in <module>
    from semantic_release.cli.cli_context import CliContextObj
  File "/psr/.venv/lib/python3.12/site-packages/semantic_release/cli/cli_context.py", line 12, in <module>
    from semantic_release.cli.config import (
  File "/psr/.venv/lib/python3.12/site-packages/semantic_release/cli/config.py", line 28, in <module>
    from semantic_release import hvcs
  File "/psr/.venv/lib/python3.12/site-packages/semantic_release/hvcs/__init__.py", line 5, in <module>
    from semantic_release.hvcs.gitlab import Gitlab
  File "/psr/.venv/lib/python3.12/site-packages/semantic_release/hvcs/gitlab.py", line 11, in <module>
    import gitlab
  File "/psr/.venv/lib/python3.12/site-packages/gitlab/__init__.py", line 30, in <module>
    from gitlab.client import Gitlab, GitlabList, GraphQL  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/gitlab/client.py", line 1279, in <module>
    class GraphQL:
  File "/psr/.venv/lib/python3.12/site-packages/gitlab/client.py", line 1286, in GraphQL
    client: Optional[httpx.Client] = None,
                     ^^^^^
NameError: name 'httpx' is not defined
```

### Environment

-  **Operating System (w/ version):** GitHub Action
-  **Python version:** 
-  **Pip version:** 
-  **Semantic-release version:** 9.8.8
-  **Build tool (w/ version):** 

<details>
<summary><code>pip freeze</code></summary>

```log

```

</details>

<br>

<details>
<summary><code>git log --oneline --decorate --graph --all -n 50</code></summary>

```log

```

</details>

### Configuration

<details>
<summary>Semantic Release Configuration</summary>

```toml
```

</details>
<br>

<details>
<summary>Build System Configuration</summary>

```toml
```

</details>
<br>

<details>
<summary>GitHub Actions Job Definition</summary>

```yaml

```

</details>

### Execution Log

<details>
<summary><code>semantic-release -vv <i>command</i></code></summary>

```log

```

</details>

**Comment by mmiller-max** [comment]
This error seems to be resolved with python gitlab `4.11.1`. [This](https://github.com/python-gitlab/python-gitlab/issues/2981) is the associated issue that was closed with the release.

**Comment by nejch** [comment]
Hi all, python-gitlab maintainer here, and I caused this issue 😅 

I just want to say that release has already been yanked and the latest 4.11.1 no longer has this issue.

httpx does not need to be installed as it's only part of the optional graphql client.

However to avoid these kinds of issues in the future I suggest locking dependencies in the GH action. I already opened https://github.com/python-semantic-release/upload-to-gh-release/issues/25 earlier today.

**Comment by codejedi365** [comment]
@kwevers, thank you for the rapid bug report.  Unfortunately, it is not my project to fix as it is a missing dependency definition in one of our dependencies. The primary fix to make on my part is to add a dependency definition that eliminates the selection of the broken release version of `python-gitlab`.

As we have seen that the `python-gitlab` owner has already corrected the mistake and better yet yanked the failed version from PyPi, we no longer need to make any changes.

Unfortunately, the solution for using a lockfile to avoid this in the future is not viable for python-semantic-release holistically and unfortunately an unavoidable issue across the python ecosystem.  This circumstance highlights the importance of runtime testing before release and the flaw with external dependencies and automated dependency resolution.
