### ISSUE TITLE
Unexpected formatting in changelog from default template

### ISSUE THREAD

**Issue by clarkecheckr** [python-semantic-release/python-semantic-release#1047]
## Question
Where in the CHANGELOG.md.j2 template is the formatting for Conflicts? I've looked but can't find it. Conflicts seem to not match the formatting so well and I'd like to change it for my project. I've made other changes and can see them in the CHANGELOG.md after release, but I can't find the Conflicts formatting.

![image](https://github.com/user-attachments/assets/ce5fb257-c14d-4f9b-a20a-d359fb4bdea0)

## Additional context
I'm using a typical configuration where my CHANGLOG.md.j2 is in a directory name templates, and the template is the default that was downloaded from the git repo.

**Comment by codejedi365** [comment]
That conflicts portion is inside of your commit.

**Comment by codejedi365** [comment]
One recommendation which would eliminate the Unknown category is to set the `semantic_release.changelog.exclude_commit_patterns` list to include regular expressions that will ignore posting irrelevant commit messages (which ultimately did not help determine the version).

PSR uses the following:
https://github.com/python-semantic-release/python-semantic-release/blob/master/pyproject.toml#L389-L400

**Comment by clarkecheckr** [comment]
I added the exclude_commit_patterns and it looks much better. I did a couple of squash commits on the MR and a new version was not created. Is this what you mean by not supporting squash commits?

**Comment by codejedi365** [comment]
Yes that is correct

**Comment by codejedi365** [comment]
Yes the version determination does not comprehend squashed commits and subsequently the default template does not have a way to construct a complete set of changes without printing the entire body of the commit message. 

This is why your merge commit with the `# conflicts:` line was printed in the resulting changelog.

**Comment by clarkecheckr** [comment]
Is handling squash commits versioning properly on the roadmap for python-semantic-release?

**Comment by codejedi365** [comment]
Yes, parsing out multiple commits messages inside one commit message  is in work.

**Comment by clarkecheckr** [comment]
@codejedi365, what do you think the timeline is for handling squash commits?

**Comment by codejedi365** [comment]
> @codejedi365, what do you think the timeline is for handling squash commits?

Given my time and the amount of work it will take, it will be at least a month if I don't get additional urgent fixes that come in. I already have a prototype but the testing is complicated.
