### ISSUE TITLE
An error occurred in the workflow

### ISSUE THREAD

**Issue by michaelbennn** [python-semantic-release/python-semantic-release#1074]
### Description

I am going to use python-semantic-release to perform CICD operations in gitea action, but it reports an error and it keeps this error

![image](https://github.com/user-attachments/assets/c259ef3c-0d2c-474e-a722-2e632ea5c9f4)

this is workflow.
![image](https://github.com/user-attachments/assets/43cb031d-55ca-41ba-ae5a-8fcf70c65fa4)

### Environment

-  **Operating System (w/ version):** 
-  **Python version:** 
-  **Pip version:** 
-  **Semantic-release version:** 
-  **Build tool (w/ version):** 

<details>
<summary><code>pip freeze</code></summary>

```log

```

</details>

<br>

<details>
<summary><code>git log --oneline --decorate --graph --all -n 50</code></summary>

```log

```

</details>

### Configuration

<details>
<summary>Semantic Release Configuration</summary>

```toml
```

</details>
<br>

<details>
<summary>Build System Configuration</summary>

```toml
```

</details>
<br>

<details>
<summary>GitHub Actions Job Definition</summary>

```yaml

```

</details>

### Execution Log

<details>
<summary><code>semantic-release -vv <i>command</i></code></summary>

```log

```

</details>

**Comment by codejedi365** [comment]
@michaelbennn, that error is trying to let you know that there is an error in your configuration specifically in the remote configuration section. 

Can you fill out the bug template with your configuration at least? The boilerplate is supposed to help me determine the issue and provide a solution. 

The specific error is detecting that you have configured a HTTP URL of some kind and have not set the `remote.insecure` flag to true to enable it.

**Comment by codejedi365** [comment]
Also don't point at the master branch, always point at a specific tag when defining an action. If I introduced breaking changes or even just had master branch in a broken state, you would have a broken pipeline.

**Comment by codejedi365** [comment]
### :tada: This issue has been resolved in Version 9.18.1 :tada:

You can find more information about this release on the [GitHub Releases](https://github.com/python-semantic-release/python-semantic-release/releases/tag/v9.18.1) page.
