### ISSUE TITLE
Trusted Publishing Failure

### ISSUE THREAD

**Issue by codejedi365** [python-semantic-release/python-semantic-release#1082]
@relekang, Looks like I messed up the trusted publisher configuration for publishing to PyPI.  I improved the github action workflows and ended up changing the name of the workflow file from `main.yml` to `cicd.yml`.  I did not know that the job workflow was a part of the claim set related to trusted publisher configuration.

You can see here how the job failed: https://github.com/python-semantic-release/python-semantic-release/actions/runs/11655716009/job/32451229646

Can you update the trusted publisher configuration with PyPI? After you do, I will re-run the release job.  (I have already removed/reversed the tag and vcs release).  Thanks

If you would help me keep the repo clean could you force push master to remove the 9.12.1 release commit as I am unable to force push to the default branch

**Comment by relekang** [comment]
This should be fixed on the pypi side now

**Comment by codejedi365** [comment]
thank you, it worked!
