### ISSUE TITLE
How to configure for GitHub Enterprise Server Releases

### ISSUE THREAD

**Issue by berndku** [python-semantic-release/python-semantic-release#1114]
### Description
Publishing a release on [GitHub enterprise server (GHES)](https://docs.github.com/en/enterprise-server) results in an error message when setting `semantic_release.remote.type = github`. 

```
404 Client Error: Not Found for url: https://api.github.com/repos/<org>/<repo>/releases
```
Reason is that the URI for GHES is different than for github.com. 

### Use cases
Support users on GHES. 

### Possible implementation
- Add a new type for ghes
- Add a new configuration parameter for the GHES HOSTNAME
- Build the URI for creating the release like described [here](https://docs.github.com/en/enterprise-server@3.15/rest/releases/releases?apiVersion=2022-11-28#create-a-release). Scheme:   http(s)://HOSTNAME/api/v3/repos/OWNER/REPO/releases

**Comment by codejedi365** [comment]
This is actually already supported, see if you can configure the api domain and domain config values as specified on the configuration page of the documentation.

**Comment by codejedi365** [comment]
I don't have in-depth docs on how to configure it for on-prem enterprise server but you may take a look at the hvcs/github.py implementation as it will make decisions to adapt to enterprise server rather than the GitHub.com

**Comment by codejedi365** [comment]
Discussed in #895 & #896. Specifying the `tool.semantic_release.remote.domain` should do the trick (as long as its not `github.com` on an internal LAN or something). It also will read the GITHUB_SERVER_URL, GITHUB_API_URL env variables if a domain value is not specified in the configuration and the variable exists. Let me know if you solve your problem (or just close the issue)

**Comment by berndku** [comment]
Thanks for the fast response. Indeed, setting the 'domain' resolved the issue.

**Comment by codejedi365** [comment]
Great to hear, enjoy!
