### ISSUE TITLE
semantic release version automated commit message failing commit validation

### ISSUE THREAD

**Issue by jspruance** [python-semantic-release/python-semantic-release#1129]
I am using commitizen in a pre commit hook to validate commit messages used by python-semantic-release, to ensure that they conform to the conventional commits spec.

It looks like commitizen is failing the auto-generated python-semantic-release commit messages resulting from a 'semantic-release version' command. (ex commit message: "0.3.1").

Question - Is there a way to either edit the auto commit message template or add an exception to commitizen to allow these kinds of messages to pass validation? What is the best practice around this? Thanks.

**Comment by codejedi365** [comment]
@jspruance, probably the easiest is to set the `commit_message` configuration option to change the default version release commit message. See [Configuration](https://python-semantic-release.readthedocs.io/en/stable/configuration.html#commit-message).

I do think it is odd that you are not filtering commits between two hashes via the parameters to commitizen check. In most cases I approach the problem as I want to use commitizen against the current unreleased changes to ensure my version determination works as expected come the next release.

**Comment by jspruance** [comment]
@codejedi365 I'll experiment with customizing the commit message first. Thanks for the reply and link.

**Comment by codejedi365** [comment]
@jspruance, you're welcome and let me know if it works out for you. Likely you will just need to add a prefix like `chore(release): {version}`.

**Comment by jspruance** [comment]
It did work! I added 'ci: {version}'. Thanks again : )
