### ISSUE TITLE
Add links to github/gitlab issues in changelog

### ISSUE THREAD

**Issue by nicholasamorim** [python-semantic-release/python-semantic-release#194]
commitizen allows you to specify a ticket number at the end of the process. This information is stripped from the changelog output.

How can I add it?

**Comment by relekang** [comment]
Do you have an example commit?

**Comment by nicholasamorim** [comment]
```
    build(automation,nginx,errbot): errbot conf now uses Ceph mountpoint. Added nginx errbot files

    MapR broke errbot because the configuration was stored on it. This commit changes the location of
    the data. In the past, I forgot to add errbot's nginx files - necessary for authentication.

    fix #5238
```

**Comment by achary** [comment]
I would say, supporting arbitrary pattern as a issue link would be very useful here, so not only hard-coding to Gitlab/Github issues.

For example, some organisations use exteral issue tracking systems. Linking to those would make a lot of sens and help in adoption.

## Proposal
The arbitrary, user-defined URL scheme could be given as a config key, perhaps templated with `{issue_number}` placeholder like this:
```
// in pyproject.toml
external_issue_url = "http://some.url.com/browse/{issuse_number}"
```

The following example commit, could then be supported:
```
    fix: No more process hang on bad inputs.

    Input data is validated before being passed down to executor. This also addresses input validation request.

    Fixes #FOO-123, #FOO-456
```

ideally producing hyperlinks to these issues respectively in the changelog:

```
...
* No more process hang on bad inputs [FOO-123](http://some.url.com/browse/FOO-123), [FOO-123](http://some.url.com/browse/FOO-123)
...

```

It would make sense, for the tool to use build-in defaults URL scheme for GitHub and GitLab issues, but when IT IS set, then a custom URL pattern should kick in.

**Comment by codejedi365** [comment]
A redesign is in progress to hopefully address this sooner than later. Likely a few more months though.

**Comment by codejedi365** [comment]
Still in the backlog.

**Comment by codejedi365** [comment]
Should be completed in the next few weeks.
