### ISSUE TITLE
Separate breaking changes from other changelog sections

### ISSUE THREAD

**Issue by danth** [python-semantic-release/python-semantic-release#244]
## Description

Pass breaking changes to components in a separate list to the changelog.

## Use cases

- Allows breaking changes to be more easily displayed using a separate component, e.g. breaking changes in a list but the changelog in a table.

## Possible implementation

Remove the `breaking` section from the changelog and give it to components as a separate list. Internally it can remain within the changelog dictionary.

**Comment by codejedi365** [comment]
No updates yet, still in the backlog, open for help from the community.

**Comment by codejedi365** [comment]
This has been templated for `v10` default changelog. Stay tuned.

**Comment by codejedi365** [comment]
Almost ready to be released, hopefully later this week.
