### ISSUE TITLE
setup_hook isn't working

### ISSUE THREAD

**Issue by artu-hnrq** [python-semantic-release/python-semantic-release#247]
## The problem

The `setup_hook` function ins't working properly

## Expected behavior

Call `semantic_release` commands via setup.py

## Additional context

Documentation says that by adding the following code in `setup.py` file it should enable the expected behavior:
```
import sys

try:
    from semantic_release import setup_hook
    print(sys.argv)
    print(setup_hook(sys.argv))
except ImportError:
    pass
```

However it seems to not be working properly. At least it hasn't achieved same behavior of call `semantic_release` directly

I'm using the following `setup.cfg` in [a `python3.8` development][1]:

```
[semantic_release]
branch = jungle
version_variable = src/kaa/__init__.py:__version__
commit_version_number = false
version_source = tag
```

  [1]: https://github.com/artu-hnrq/kaa

**Comment by artu-hnrq** [comment]
First of all, any stdout is printed when actions are called through my own `setup.py`. It's true that `version` is bumping the variable appropriately and not committing anything, as well as checking tags, as configured.

However `changelog` isn't printing nothing out either way, via `setup.py` or directly.
Look at that:

[![asciicast](https://asciinema.org/a/GdtkGAvZPiPMyKFhCpsbdJcW8.svg)](https://asciinema.org/a/GdtkGAvZPiPMyKFhCpsbdJcW8)

I looked the code a little but couldn't figure out why it's behaving that way, anyway it wasn't what I thought it would be. Is there something I misunderstood, or it is indeed not working properly?

**Comment by codejedi365** [comment]
Given that `setup.py` is slowly but surely becoming extinct, is this still an issue that needs addressing or is it obsolete?
