### ISSUE TITLE
Add support for pre-release versions and build metadata

### ISSUE THREAD

**Issue by infokiller** [python-semantic-release/python-semantic-release#267]
## Description

It seems that python-semantic-release doesn't parse pre-release versions and build metadata as specified in [SemVer 2.0](https://semver.org/#spec-item-9).

## Use cases

Releasing pre-release versions.

## Possible implementation

Change the regex parsing to support it.

**Comment by shaunc** [comment]
Would be nice if there were an option to release pre-releases as well. I have a very young project in which we would like to use semantic versioning from the start. But I wouldn't want anyone to think it was actually functional despite the high semantic version due to many breaking changes.

**Comment by codejedi365** [comment]
Prereleases are supported in the latest version `v9` and previously `v8`.
