### ISSUE TITLE
Regenerate / backfill changelog

### ISSUE THREAD

**Issue by wyardley** [python-semantic-release/python-semantic-release#286]
## Description
It would be nice to have a way to locally generate the entire changelog up to the most recent release, e.g., via
`semantic-release changelog --regenerate` or `semantic-release changelog --regenerate > CHANGELOG.md`.

I think this has been alluded to in some previous threads, but they predate the current changelog implementation, and don't seem to be open currently.

## Use cases
* Backfilling in cases where the changelog didn't already exist (or where changelog generation didn't exist previously) (obviously this still won't work if conventional / semantic commits weren't used)
* Regenerating the entire changelog in the case that something gets messed up, or to have consistent formatting if / when improvements or changes are made in the changelog format

## Possible implementation
I took a pass at adding it in the cli section via a `--regenerate` option. I'm seeing something odd with going backwards (at least using this project's tags as an example), which I'll put more details of in the logs. Testing could be a little tricky, but code-wise, had been thinking thinking of something like this

https://github.com/relekang/python-semantic-release/blob/b7e1376ee1688e5e6dcc069ce623f49e3a389052/semantic_release/cli.py#L183

```python
    if unreleased:
        logs.append(generate_changelog(current_version, None))
    elif regenerate:
        logs.append(generate_changelog(previous_version, current_version))
        # Now walk backwards until we get to the first version
        while current_version:
            # I assume this is, or could made to be, None at the point where there's no previous version
            # however, with this project, it's going from 0.5.0 back to 3.1.0, and gets into a loop
            current_version = previous_version
            previous_version = get_previous_version(current_version)
```
would love some suggestions for a) if there's an issue with `get_last_version()` or `get_previous_version()`, or if this is just wonkiness with the tags (even if it were, we'd need some way to avoid getting in an infinite loop - maybe a new function `get_all_tags()`, and try to get the previous version for each of those?

**Comment by wyardley** [comment]
https://github.com/relekang/python-semantic-release/compare/master...wyardley:wyardley-backfill-changelog?expand=1 
is a little closer, and almost works (the hard-coded 2.0.0 break is a hack to deal with the issue mentioned above).

For this project, still seems to be off by one for certain tags, and can't get dates for certain tags.

**Comment by Doggie52** [comment]
Would be extremely useful to have something like this.

Reason being, I set up the latest version of the package on an existing repo where I had been making commits using the angular prefixes. When I ran `publish`, it tagged a version, committed an update to my version variable **but didn't add anything to my changelog**. Just to confirm - is this indeed currently the intended behavior?

If so, I presume this issue will allow me to backfill my changelog, which would solve my issue.

**Comment by wyardley** [comment]
@Doggie52 yeah
For a single release, you may be able to trick python-semantic-release to generate the last release's changelog (maybe try checking out right before the tag?), but you can also use the node conventional-changelog-generator to generate a pretty similar changelog via something like `npx conventional-changelog -p angular -i CHANGELOG.md -s -r 0` (and then just add the placeholder above it).

**Comment by wyardley** [comment]
I think this is now possible.

**Comment by Doggie52** [comment]
How is it possible? Is it done automatically?

**Comment by codejedi365** [comment]
Should be able to use the following command to create a changelog.

```sh
semantic-release changelog
```

After v8, the entire changelog is generated by default and default functionality to do an insertion of the latest release was removed.
