### ISSUE TITLE
Configurable tag names

### ISSUE THREAD

**Issue by matteosantama** [python-semantic-release/python-semantic-release#316]
## Description

Currently when a commit is tagged, the tag name and message are both fixed to the version number.

https://github.com/relekang/python-semantic-release/blob/1dd84847a9eaf8d2467ae5b4ee82492ef563612f/semantic_release/vcs_helpers.py#L198-L204

It would be nice if the user were able to configure a template for the tag name or message.

## Use cases

One major use case would be when `python-semantic-release` is being used in a staging environment. The tags could take the form `vX.Y.X-staging`. Note that this would not be a prerelease specification. `python-semantic-release` only supports versioning at the `major`, `minor`, and `patch` levels so this would template would live outside the scope of semantic versioning. It would exist solely as git tags.

## Possible implementation

https://github.com/relekang/python-semantic-release/blob/18e1d70138125f93664f3c9b3c1e08c57f392977/semantic_release/cli.py#L173-L187

The calling function already has access to the config variables, so it would be straightforward to add a `tag_template` configuration variable.

**Comment by jacksbox** [comment]
This would be nice feature indeed. Currently I have the same usecase.

I could imagine having a `--prefix` and `--suffix` cli (and config) option when bumping.
Maybe a `--project` option as well, to make `semantic-release` easier usable with monorepos (see https://github.com/relekang/python-semantic-release/issues/168) 😉 

Would this be an interesting feature? I could try to implement this...

**Comment by codejedi365** [comment]
I believe this issue was resolved a while back as we currently have a tag format configuration setting which defines custom tags. I was not around when it was implemented so if I am incorrect in this conclusion, please let me know.
