### ISSUE TITLE
Add support for GitLab merge requests pipeline

### ISSUE THREAD

**Issue by alekseik1** [python-semantic-release/python-semantic-release#348]
Hi!
I have a GitLab project with version bumping happening on each commit to the "master" branch.
Now I'd like to set up a merge request pipeline (upon each MR to the master branch) that triggers version bump with `--noop` flag (just to make sure that once merged, this MR won't break pipeline on master's merge commit).

I faced failures with verification checks during simple `semantic-release --noop` run:
```
error: The verification check for the environment did not pass
```

It seems to me like the following check:
https://github.com/relekang/python-semantic-release/blob/20d79a51bffa26d40607c1b77d10912992279112/semantic_release/ci_checks.py#L87

does not consider merge requests at all and thus incorrectly checks branch name in a MR case. How can I make this check pass and run MR pipeline as desired?

**Comment by DenisMedeiros** [comment]
We faced the same error in Jenkins (configured with the plugin `generic webhooks` to react to pull-requests in Github). We wanted to make the build test to "build the new version" as well. Our workaround was to define the [expected environment variables](https://github.com/python-semantic-release/python-semantic-release/blob/master/semantic_release/ci_checks.py#L112) from another available variable:

```groovy
 steps {
   script {
        sh 'pip3 install -r requirements.txt'
        env.BRANCH_NAME = "${env.BASE_BRANCH}"
        sh 'semantic-release publish'
    }
 }
```

**Comment by codejedi365** [comment]
As this is a fairly old issue, I do not believe this is a problem any more. We no longer have the CI checks file and we currently support GitLab directly. Please let me know if you still need some assistance in this matter.
