### ISSUE TITLE
Allow multiple PYPI destinations

### ISSUE THREAD

**Issue by jacobolofsson** [python-semantic-release/python-semantic-release#382]
## Description

Allow multiple PYPI repositories.

## Use cases

In CI I would like to automatically publish to more than one pypi repo.

## Possible implementation
Allow the `repository` setting to accept a list of repositories, and repeat upload operation for each repo.

**Comment by fleXible** [comment]
@relekang What do you think about creating a separate `upload` command, which then just could be called several times with different `repository` or `repository_url` settings?
This would also be a good way to add an additional `--pypirc-file` switch to satisfy use case 1 from #383

**Comment by codejedi365** [comment]
Issue is now obsolete as `v8` removed `twine` uploads and it is up to the user to manage registry uploads.
