### ISSUE TITLE
Protocols cannot be instantiated

### ISSUE THREAD

**Issue by william-richard** [python-semantic-release/python-semantic-release#384]
## The problem

We are using AWS CodeArtifact to host our private packages, and we publish to that python repository by setting the `PYPI_USERNAME`, `PYPI_PASSWORD`, `TWINE_REPOSITORY_URL`, and `TWINE_REPOSITORY` environment variables before running `semantic-release publish`.  When we run this, it only outputs 1 line out output.

`error: Protocols cannot be instantiated`

## Expected behavior

The executable runs and publishes the release.

## Additional context

This error appeared in version 7.19.2 - 7.19.1 does not exhibit this error.

**Comment by vberlier** [comment]
I'm getting the same problem but with github actions and a `PYPI_TOKEN` secret. Everything worked fine a couple days ago.

**Comment by vberlier** [comment]
After investigating a bit I managed to get it working again by using an old lockfile. I tried downgrading to 7.19.1 but it didn't work for me. The problem must be coming from one of the dependencies.

**Comment by codejedi365** [comment]
As of `v8`, PSR no longer handles registry publishing with twine.
