### ISSUE TITLE
Support for adding additional items to release

### ISSUE THREAD

**Issue by rpocase** [python-semantic-release/python-semantic-release#385]
## Description

When generating a "release" (whether it be gitlab, github, or wherever), it would be nice to support uploading additional files to the release. Right now, it seems like only dist is supported (and that isn't fully cross platform based on #230)

## Use cases

The immediate use case I have in mind is for building an internal tool and publishing the documentation alongside the versioned artifacts.

## Possible implementation

All cloud source control systems have some concept of a "release" these days. Implementation will be hvcs specific.

**Comment by danth** [comment]
As a workaround you can modify [`build_command`](https://python-semantic-release.readthedocs.io/en/latest/configuration.html#build-command) to add your files to the dist folder; however I think this would cause the additional files to also be uploaded to PyPI.
