### ISSUE TITLE
--define doesn't accept booleans

### ISSUE THREAD

**Issue by osaund** [python-semantic-release/python-semantic-release#389]
## The problem

```bash
semantic-release version --define=tag_commit=false
semantic-release version --define=tag_commit=False
semantic-release version --define=tag_commit=0
```

All the above still tags the commit

## Expected behavior

Don't tag the commit

## Additional context

A workaround is 

```bash
semantic-release version --define=tag_commit=""
```
The value of the key_pair is coerced to string and therefore any value is interpreted as true. We can force it to be false by setting it to an empty string

**Comment by codejedi365** [comment]
Obsolete after `v8`. `--define` is deprecated.
