### ISSUE TITLE
Add option to write changelog in RST instead of markdown

### ISSUE THREAD

**Issue by jacobolofsson** [python-semantic-release/python-semantic-release#399]
## Description

Allow user to specify format of changelog to either md or rst (could be extended to other formats as well).

## Use cases

I usually use sphinx/rst to document my python projects. For consistency I also write README, CONTRIBUTING etc in rst, which also makes it trivial to include these files in the documentation itself.

It would be great if I could do the same for the changelog (and also consistent, since the changelog is the only md file among all my rst files)

## Possible implementation

* Add a `changelog_format` option (or maybe decide based on `changelog_file` suffix)
* Add a `rst_changelog()` function in `semantic_release/changelog/__init__.py`

**Comment by steven-murray** [comment]
From a cursory look, it seems that this would be slightly difficult, because the `markdown_changelog` function just concatenates the outputs from the various `component` functions. This would mean all those functions would require RST counterparts. 

Instead, if an extra dependency is OK, one could use `pandoc` on the final output?

**Comment by codejedi365** [comment]
Still in the backlog and I have been considering knocking this out quickly as I would like it to include the changelog on the website which uses sphinx RST files. Hopefully soon as I have time available.

**Comment by codejedi365** [comment]
Since we also now use jinja for file templating and provide a custom rendered folder you can do this today (>v8) with your own template.

**Comment by codejedi365** [comment]
I have effectively accomplished a RST template for changelogs and should come out with the new changelog templates in upcoming versions.
