### ISSUE TITLE
Improvement: Single source of version truth

### ISSUE THREAD

**Issue by jacksbox** [python-semantic-release/python-semantic-release#424]
## Description

Note: This ticket is purely about implementation.
Currently the version numbers are determined via multiple ways depending on the config and the called method. 
Depending if `get_current_version`, `get_next_version`, and more, different ways to determine this version are used:
based on tags, based on parsed commit messages, the version file (and maybe more?).
I understand the need for this in the current implementation, but it feels a bit error prone and I think it would make the code easier and cleaner if we could come up with a single way how versions are determined / parsed / found.

I would like to open a discussion about this...

**Comment by danth** [comment]
If tags are always created, regardless of the `version_source` setting, then it would make sense to only use those to read the version.

**Comment by jacksbox** [comment]
@danth jup, tags would need to always be created. I think that is a fair requirement (in the future we could think of a plugin solution to enable different and more complex version sources)...

This breaks with a feature I introduced as well -> https://github.com/relekang/python-semantic-release/pull/341, but as stated in the PR, this was for the usecase of monorepos, something this package is currently not made for and also probably should not be used for. So I would be fine with removing this features again.
(the whole prerelease feature seems to be a lot more useful and for a bigger audience as well)

**Comment by triplem** [comment]
One more feedback on this one. The chamgelog seems to still rely on commit messages which would be against the single source of truth as well IMHO.
So the chamgelog should determine the log messages based on Tags as well.

**Comment by bernardcooke53** [comment]
@jacksbox I'm working my way through refactor & would love your input (+ feedback down the line) - I have #487 open for it

**Comment by nejch** [comment]
Just another voice here for using tags if possible (I see there were discussions about monorepos, but maybe another way to parse that makes sense).

I'd actually get rid of `get_current_release_version_by_commits` entirely - people use dependabot/renovate and it seems like that could always interfere when other semvers appear in commits, as well as changing commit message patterns throughout the history of a project etc. I also had trouble migrating an existing project using this approach, as there's no good way of reusing changelogs/tags to bump versions while still committing things.

There seems to be some refactoring going on and I haven't full read all the context so sorry if this is a repeat :) I help maintain python-gitlab and we use each other's libraries so I'd definitely like to have things work smoothly, will try to contribute at least some gitlab-related stuff if you decide to keep that in the core library.

**Comment by relekang** [comment]
@nejch I think this is already happening as a part of #487 👍

**Comment by bernardcooke53** [comment]
This is definitely happening in #487 - it will be tags only. @nejch the Gitlab implementation in PSR is definitely lagging behind Github and Gitea - would be great to have your input!

**Comment by codejedi365** [comment]
Implemented with the release of `v8`.
