### ISSUE TITLE
The version number will be confused when use `--prerelease` option

### ISSUE THREAD

**Issue by donhui** [python-semantic-release/python-semantic-release#434]
## The problem

The version number will be confused when use `--prerelease` option:
<img width="726" alt="image" src="https://user-images.githubusercontent.com/5702065/161038804-8e6c5641-0585-4a79-80f7-edf826e58738.png">

## Expected behavior

The version number is incremented in the normal way.

## Additional context
When I execute this command many times, there is a problem with the version number, the log as follows:
```
(venv) pydemo % semantic-release version  --prerelease 
Creating new version
Current version: 0.3.5
Bumping with a None version to 0.3.5-beta.3
(venv) pydemo % semantic-release version  --prerelease
Creating new version
Current version: 0.3.6
Bumping with a None version to 0.3.6-beta.4
(venv) pydemo % semantic-release version  --prerelease
Creating new version
Current version: 0.3.5
Bumping with a None version to 0.3.5-beta.5
(venv) pydemo % semantic-release version  --prerelease
Creating new version
Current version: 0.3.6
Bumping with a None version to 0.3.6-beta.6
```

semantic_release config in `pyproject.toml`:
```
[tool.semantic_release]
version_toml = "pyproject.toml:tool.poetry.version"
```

**Comment by jacksbox** [comment]
@donhui I reworked the prerelease feature in this PR: https://github.com/relekang/python-semantic-release/pull/435
My local tests gave the correct results, maybe you run your example again with the the code from this branch to make sure it works?
(also, it will only work if all version bumps are done on the same branch)

**Comment by FlorentGodin** [comment]
Hello,

How does it work when you use the command `semantic-release version --prerelease` multiple times ? 
The first time I got a correct version (like 1.1.0-beta.0) but next, it tells me `error: no versions found in the configured locations`. It seems it comes from the parsing (the regex does not include prerelease).

My pyproject.toml :
```toml
[tool.semantic_release]
version_variable = [
    "src/dummy_package/__init__.py:__version__",
]
```

Do I forget something ?

**Comment by FlorentGodin** [comment]
Thanks @jacksbox!
