### ISSUE TITLE
IP address is parsed into version number

### ISSUE THREAD

**Issue by chbndrhnns** [python-semantic-release/python-semantic-release#474]
## The problem

My commit title is this: 
'Use 127.0.0.1 as base_url for test client'

The output is this:

```
debug: parse_commit_message('fix: Use 127.0.0.1 as base_url for test client')
debug: parse_commit_message -> ParsedCommit(bump=1, type='fix', scope=None, descriptions=['Use 127.0.0.1 as base_url for test client'], breaking_descriptions=[])
debug: Commits found since last release: 2
debug: evaluate_version_bump -> patch
debug: get_new_version('4.28.3', '127.0.0', 'patch', False)
```

## Expected behavior

The tool does not pick up an IP address for a version number

**Comment by leonardo-deoliveirasaldanha-oxb** [comment]
Any progress so far?

**Comment by bernardcooke53** [comment]
Hey - this should be fixed in [the next major release](https://github.com/python-semantic-release/python-semantic-release/issues/487)

**Comment by leonardo-deoliveirasaldanha-oxb** [comment]
Thanks for the prompt response, @bernardcooke53 ! Looking forward to it

**Comment by chbndrhnns** [comment]
@bernardcooke53 can you tell if this fix has been included in the release you mentioned?

**Comment by codejedi365** [comment]
> can you tell if this fix has been included in the release you mentioned?

@chbndrhnns, as of `v8` (July 16, 2023), commit messages are no longer used to extract version numbers, only tags are used. I reviewed the code again to confirm. The commit messages are evaluated for other indicators to determine which new version number will be created based on the commit parser chosen. With this said, I believe that your issue will no longer occur.
