### ISSUE TITLE
Repository username and password should not be required

### ISSUE THREAD

**Issue by worawatwi** [python-semantic-release/python-semantic-release#496]
## Description

*The ArtifactRepo verify that repository_username and repository_password must be set before uploading the distribution.*

## Use cases

*Google Artifact Registry Python repository does not use username and password for authentication (as describe in https://cloud.google.com/artifact-registry/docs/python/authentication#keyring) so it should be possible to not specify username and password for custom repository.*

## Possible implementation

*The repository_username and repository_password should not be required.*

**Comment by bernardcooke53** [comment]
@worawatwi have you tried setting the config option `repository_pass_var = "GOOGLE_APPLICATION_CREDENTIALS"`? (From a cursory look at the docs) I assume this request isn't about supporting some kind of totally unauthenticated upload.

**Comment by codejedi365** [comment]
As of `v8`, PSR no longer handles twine upload configurations.
