### ISSUE TITLE
Allow for force push to git repo

### ISSUE THREAD

**Issue by cameronwaterman** [python-semantic-release/python-semantic-release#532]
## Description

Add a configuration that instructs the `git push` command to `--force` push.

## Use cases

I'm trying to configure `python-semantic-release` to push to my protected main branch. Even with an admin access token that is allowed to bypass PR policies, the branch protection still requires a set of checks to pass before a commit is allowed. GitHub does however have a configuration that allows force push for certain users. I can tell the tool to force push, and configure my repo to allow the CI user to force push to the protected branch.

## Possible implementation

Add a configuration and CLI option `--commit-force`

**Comment by cameronwaterman** [comment]
It looks like https://github.com/python-semantic-release/python-semantic-release/issues/311 actually fixed my issue. It might still be worth considering adding this option though 😄 Thanks!

**Comment by codejedi365** [comment]
No update yet, still in the backlog

**Comment by codejedi365** [comment]
No change, still in backlog.

**Comment by codejedi365** [comment]
No update yet, still in the backlog.

**Comment by codejedi365** [comment]
After more careful consideration, I would rather not implement this as this project is run with write permissions to someone's repo. Given some malicious intent this potentially could wipe out someone's repository in an automated fashion. 

As you mentioned above, you were able to solve your issue another way so I don't have another compelling reason to implement this that overrules the security issue above.
