### ISSUE TITLE
Can't use version_source = "tag" alone

### ISSUE THREAD

**Issue by Narthe** [python-semantic-release/python-semantic-release#534]
## The problem

I have a specific python project that I don't build a wheel from and I don't have a setup.py file either.
I can't use `version_source = "tag"` alone without setting any of 'version_variable', 'version_pattern' or 'version_toml' due to the following error :
`error: must specify either 'version_variable', 'version_pattern' or 'version_toml'`

## Expected behavior

I would like to tell python-semantic-release to only use tags as the source for the versions but I don't need the new version written or stored anywhere in a file.

## Additional context

```
[tool.semantic_release]
version_source = "tag"
hvcs = "gitlab"
branch = "ci/my-ci-testing-branch"
build_command = false
upload_to_repository = false
```

**Comment by bernardcooke53** [comment]
Hey - no worries. Just wanted to leave a note that in the next major version of PSR this should be possible, as we are sourcing the version information only from the Git tags - therefore having somewhere to write it to will then be optional.
