### ISSUE TITLE
Add option to prevent commit/push to repository

### ISSUE THREAD

**Issue by danieljamesscott** [python-semantic-release/python-semantic-release#537]
## Description

Add an option to avoid committing/pushing to the GitHub repo

## Use cases

We enable main branch protection so it's not possible to commit/push on the `main` branch directly. It would be great to use semantic release to build a versioned package (and upload/tag it as a GitHub release) but not commit and push in the repository.

## Possible implementation

Add a `--no-commit` flag.

**Comment by bernardcooke53** [comment]
Hi @danieljamesscott - I've added a `--no-commit` flag to an upcoming major release, hopefully that will meet your use case!
