### ISSUE TITLE
allow multiple version file handlers at the same time

### ISSUE THREAD

**Issue by benedikt-bartscher** [python-semantic-release/python-semantic-release#539]
## Description

Currently you can either use version_variable or version_pattern or version_toml. However you can use multiple files with the same "plugin". So a fix is to just use version_pattern for everything. But it would be much cleaner to use version_variable, version_pattern and version_toml in parallel.

`error: must specify either 'version_variable', 'version_pattern' or 'version_toml'`

**Comment by bernardcooke53** [comment]
Hi 👋 

You should be able to specify any of those as you need to, the error message means you need to specify _at least_ one 😊

Have you tried using more than one and hit an error?
