### ISSUE TITLE
404 to find url for release

### ISSUE THREAD

**Issue by LADIESDIV** [python-semantic-release/python-semantic-release#542]
Hey !
I use a private repository and I can't create release because I have a 404 to find repository. 
URL it's ok (curl ok in my laptop) so I think I don't set github token correctly.

Can you help me to set token github correctly please ? I use github action :

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@v7.32.2
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        additional_options: ${{ inputs.opt_arg }}
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        
Thinks !

**Comment by bernardcooke53** [comment]
Hey @LADIESDIV :wave:! Could you please add the logs from the output of the GitHub action?

**Comment by LADIESDIV** [comment]
Yes :
debug: create_release(<class 'semantic_release.hvcs.Github'>, '$ORG', '$REPO_NAME', 'v1.0.7', '### Fix
debug: * Release ([`3ef89cf`](https://github.com/$ORG/$REPO_NAME/commit/3ef89cf30d2dcf34b9e95eface14852cae43bb63))')
warning: Release creation on Github has failed: 404 Client Error: Not Found for url: https://api.github.com/repos/$ORG/$REPO_NAME/releases
debug: create_release -> False

**Comment by bernardcooke53** [comment]
Thanks - would you also be able to add on the curl command and your `semantic-release` configuration?

**Comment by LADIESDIV** [comment]
Yes :
curl command : curl -H "Accept: application/vnd.github+json" -H "Authorization: ***" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$ORG/$REPO_NAME

and semantic config in pyproject.toml (with github token in github action)  :
[tool.semantic_release]
version_variable = "setup.py:__version__"
branch = "feat/addci"
upload_to_pypi = false

**Comment by bernardcooke53** [comment]
I've had a thorough check and I'm not sure this is an issue with Python Semantic Release - looking at the Actions docs [here](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow) and [here](https://docs.github.com/en/actions/learn-github-actions/contexts#secrets-context), could you please try using `{{ secrets.GITHUB_TOKEN }}` instead of `{{ secrets.GH_TOKEN }}` and see if that works? Assuming you aren't setting a custom secret on the repository under `GH_TOKEN`.

**Comment by LADIESDIV** [comment]
I can't create secret "GITHUB_TOKEN" : Failed to add secret. Secret names must not start with GITHUB_.  
So it's ok with GH_TOKEN !
Sorry I'm bad, I use reusable CI and I write bad secret...
Thinks for I help !

**Comment by LADIESDIV** [comment]
Hey !
It is possible to add other variable that "GH_TOKEN" in github action secret to make release works please ?
In my organization, github token doesn't have "GH_TOKEN" name...
Thanks !

**Comment by bernardcooke53** [comment]
Hi, the docs seem to suggest that a "GITHUB_TOKEN" variable is automatically created for you to use for authentication within a Github action to act against the repository - have you tried changing your workflow to use GITHUB_TOKEN without trying to add it as a repository secret first?

**Comment by LADIESDIV** [comment]
It's ok, I see with github admin entreprise and It's ok know.
Thanks !
