### ISSUE TITLE
Changelog not working unless I use the --unreleased flag

### ISSUE THREAD

**Issue by ademoverflow** [python-semantic-release/python-semantic-release#543]
## The problem

This is my git history at the moment:

```
3e7ea70   4 days ago User XXX (HEAD -> master, origin/master, origin/HEAD, semver) fix: repo-init does not clean codebase properly
fbfdcda   4 days ago User XXX chore: add .keep files in empty directory for docs
cd25db6   6 days ago User XXX feat(docs): autogenerate docs with sphinx and apidocs
184d5a3   5 days ago User YYY misc: makefile: del unnecessary var
201cd18   5 days ago User YYY fix: makefile: no need to set TZ in container
2840520   7 days ago User YYY feat: set timezone in docker without mounting from host
56b389e   7 days ago User YYY feat: generate docker-compose .env from makefile
cd7545e   7 days ago User YYY fix: wrong makefile phony
52f9641   7 days ago User XXX fix(initialization): write .TEMPLATE_VERSION
3b2f05d   7 days ago User XXX feat(initialization): Generate .TEMPLATE_VERSION file automatically + reset project version on init
4484142   7 days ago User XXX chore: remove unused file
40340ae   7 days ago User XXX feat(dev container): allow user to run commands as sudo, without any password prompt
13591aa   7 days ago User XXX (tag: v0.0.0) feat: configure python-semantic-release
1983ee6   7 days ago User YYY docs: -del doc about makefile-in-docker env var
eeb7f31   7 days ago User YYY feat: detect makefile is run in a docker container
a9026a0   7 days ago User XXX fix: remove forgotten doc for git-chglog
24847d0   8 days ago User XXX fix: remove also empty folders
34b4d2d   8 days ago User XXX fix: remove code base wrong path
7eeac63   8 days ago User XXX chore: remove template codebase at repo init
c7d2802   8 days ago User XXX fix: use -p in read call to avoid separate echo
7a00a69   8 days ago User XXX feat: remove unused step + add the possibility to create or not a git repository within the project
20b681b   8 days ago User XXX chore: delete unused
```

When I launch `semantic-release changelog`, generated changelog is **empty**. When using `--unreleased`, this changelog is generated:

```
### Feature
* **docs:** Autogenerate docs with sphinx and apidocs ([`cd25db6`](https://github.com/my-repo/my-repo/commit/cd25db64bff3a5a5cbdb033d8e94c9eb68dbc3d8))
* Set timezone in docker without mounting from host ([`2840520`](https://github.com/my-repo/my-repo/commit/28405205b9d527b996b7f08537b8700d6a4dd3aa))
* Generate docker-compose .env from makefile ([`56b389e`](https://github.com/my-repo/my-repo/commit/56b389e730067f1a2849143e62c50a83e69cb5a3))
* **initialization:** Generate .TEMPLATE_VERSION file automatically + reset project version on init ([`3b2f05d`](https://github.com/my-repo/my-repo/commit/3b2f05d1dacc6cde2ccce2d272e2c885151dc912))
* **dev container:** Allow user to run commands as sudo, without any password prompt ([`40340ae`](https://github.com/my-repo/my-repo/commit/40340ae3d5617d83ab26127e4e9d4fe003a91ac1))

### Fix
* Repo-init does not clean codebase properly ([`3e7ea70`](https://github.com/my-repo/my-repo/commit/3e7ea7020418e6065a4f376353f89ee6334462ff))
* Makefile: no need to set TZ in container ([`201cd18`](https://github.com/my-repo/my-repo/commit/201cd18d780d5405f646d387d84367611e58c485))
* Wrong makefile phony ([`cd7545e`](https://github.com/my-repo/my-repo/commit/cd7545ebe8cc521ee2a12e6af2da810f5e0f7a7f))
* **initialization:** Write .TEMPLATE_VERSION ([`52f9641`](https://github.com/my-repo/my-repo/commit/52f9641d219276786a706b1fac2233949af0dabd))
```

## Expected behavior

Without using `--unreleased`, the tool should give me the changelog, or there is a problem with the documentation / tool.
Indeed, `publish` command documentation describes the steps, and the first one is generating the changelog **BEFORE** creating the new version. So I wanted to execute commands step by step to check that it is working properly, but it's not.

Maybe I did something wrong ?

## Additional context

The first version and tag on my project (pyproject.toml) was not created with semantic-release. Maybe this can be a problem ?

Also, while digging the code, those lines in `cli.py` look odd to me:
https://github.com/python-semantic-release/python-semantic-release/blob/a4b625f98da8b4d9364f6dd37260d92a24238cf6/semantic_release/cli.py#L287

Is it possible that the two parameters should be switched ? Looking at the function documentation, there may be an error or I'm just lost at trying to figure this out ?

Thank you for your help !

**Comment by bernardcooke53** [comment]
Hey :wave: 

I think this is expected behaviour - `changelog` just produces a changelog structured version-by-version, but PSR tries to identify when the last version was by looking for its own commit. Because you haven't yet done a release with PSR, it doesn't think that _anything_ has been released yet, so you get an empty changelog unless you add the `--unreleased` flag.

In `publish` the new version is calculated [before the changelog is generated](https://github.com/python-semantic-release/python-semantic-release/blob/a4b625f98da8b4d9364f6dd37260d92a24238cf6/semantic_release/cli.py#L334), and the [changelog contents](https://github.com/python-semantic-release/python-semantic-release/blob/a4b625f98da8b4d9364f6dd37260d92a24238cf6/semantic_release/cli.py#L358) is essentially the summary of commits since the previous release, up until this new version, which gets substituted into the changelog file (during `publish`) wherever the `<!--next-version-placeholder-->` comment is.

**Comment by ademoverflow** [comment]
Thank you for your answer.

I used `publish` command and it created the right changelog for version v0.1.0.
Now, I want to release a new version, but I do not want to use publish as it includes Github links for each commit and I'm not using GitHub neither Gitlab. So if I launch `version` it creates the right next version and updates it well, but even after that `changelog` is not working. So what's the issue there ?

**Comment by bernardcooke53** [comment]
When you say:

> but even after that changelog is not working

what do you mean? Are you getting an empty changelog, or is it ok up until v0.1.0 but then missing anything else?
Can you post your configuration? And could you please make sure that you've got a `<!--next-version-placeholder-->` in your changelog?
