### ISSUE TITLE
Can semantic release be used without publishing the artifact?

### ISSUE THREAD

**Issue by drorrose** [python-semantic-release/python-semantic-release#548]
I want to use this tool from my CI pipeline, only to set up a version and update changelog. Further steps in the CI pipeline should be a docker image and publish it to a private container registry. 

I wonder if there is a way to do so, or if there is a better way to use the tool to achieve the result I described above?

**Comment by bernardcooke53** [comment]
Hey :wave: 

Sure - try setting `upload_to_repository`, `upload_to_pypi` and `upload_to_release` all equal to `False` in your configuration - that should disable publishing the artefact. Your CI pipeline can do your docker commands outside the release.

**Comment by drorrose** [comment]
Thank you so much for the response! Looking forward to using the tool!
