### ISSUE TITLE
Unable to get current release by commits in Github Actions

### ISSUE THREAD

**Issue by sp-ivan-alcoceba** [python-semantic-release/python-semantic-release#560]
## The problem

Since a few days ago we have multiple repositories where the Github Action is failing, resolving an empty SHA while doing the action and returning an error.
We tried to re-run an old job, which worked correctly and now it is failing with the same error.

Doing the action, calling directly the library with:

```bash
python -m semantic_release publish -v DEBUG -D commit_author="github-actions <github-actions@github.com>"
```
is iterating through all the commits and returning the proper version.

## Expected behavior

Expected behavior is for when semantic release runs, for it to be able to find the version in the commit.

## Additional context

Log:

```bash
debug: get_current_version_by_config_file()
debug: Regex matched version: 0.0.1
debug: get_current_version_by_config_file -> 0.0.1
debug: get_current_release_version_by_commits()
error: SHA could not be resolved, git returned: b''
##[debug]Docker Action run completed with exit code 1
##[debug]Finishing: Python Semantic Release
```

**Comment by luchinke** [comment]
Also happening to me. The only thing i could see that changed is the version of GitPython. (from 3.1.30 to 3.1.31)

**Comment by bernardcooke53** [comment]
This is going to be really difficult to debug without an environment to reproduce the issue in, as it might be dependent on specific properties of commits - is there a public example or some steps I could use to reproduce this myself?

**Comment by madpah** [comment]
@bernardcooke53 - failing with this error on https://github.com/sonatype-nexus-community/ossindex-python/commit/552a93a7876a638932e95cc5287f2efd30bc830c

**Comment by bernardcooke53** [comment]
@madpah thank you for sharing - super helpful. I noticed you're running [`relekang/python-semantic-release@v7.31.2`](https://github.com/sonatype-nexus-community/ossindex-python/blob/552a93a7876a638932e95cc5287f2efd30bc830c/.github/workflows/deploy.yml#L74) in the pipeline which is failing - there was a patch in `v7.33.1` which changed some git configuration in the Docker container used for the GitHub action ([`2a55fc8`](https://github.com/python-semantic-release/python-semantic-release/commit/2a55f68e2b3cb9ffa9204c00ddbf12706af5c070)) to account for the recent security patches to Git; looking at [this GitPython issue](https://github.com/gitpython-developers/GitPython/issues/1016#issuecomment-1104114129) I think it's a good idea to rule that out first - would you mind bumping to `v7.33.2` (and changing to reference `python-semantic-release/python-semantic-release`) and seeing if that resolves it?

On the basis of the above - @sp-ivan-alcoceba + @luchinke could you also check/update the version of `python-semantic-release` you are using please?

**Comment by sp-ivan-alcoceba** [comment]
Thanks for sharing @madpah as we didn't have any public repository to be shared. Look forward to seeing if that works.

**Comment by madpah** [comment]
@bernardcooke53 - `v7.33.2` definitely seems to resolve the issue reported.

I hit a bunch of other unrelated things now - but thanks for the time and support!

**Comment by sp-ivan-alcoceba** [comment]
Thanks @bernardcooke53 @CaibinSh @madpah.

**Comment by luchinke** [comment]
v7.33.2 also worked for me! 🚀

**Comment by jimbudarz** [comment]
I'm seeing this `error: SHA could not be resolved, git returned: b''` error when using Jenkins as well, using semantic release v7.34.6, but downgrading to v7.33.2 hasn't made a difference.
This was also the case whether the version of gitpython was 3.1.31 or 3.1.30.
