### ISSUE TITLE
Preferred way to exlude git commits vs commit types from changelog (v8)

### ISSUE THREAD

**Issue by afuetterer** [python-semantic-release/python-semantic-release#564]
Hi,

I read:
https://github.com/python-semantic-release/python-semantic-release/blob/8.0.x/docs/configuration.rst
https://github.com/python-semantic-release/python-semantic-release/blob/8.0.x/docs/changelog_templates.rst

What is the preferred way to exclude git commits or commit types (using angular commit parser) from the generated changelog in v8? For example if you don't want the commits of type "chore" shown in the changelog?

If I remove "chore" from allowed_tags in [tool.semantic_release.commit_parser_options], they will be displayed as type unknown. Is it advised to just add a "chore" regex pattern to `exclude_commit_patterns` instead or is there a way to ignore a "commit type"?

**Comment by bernardcooke53** [comment]
Hi @afuetterer ,

When I added the changelog template feature, I envisioned that it would make the changelog a lot more customisable without needing to add hundreds of configuration options into Python Semantic Release itself.

To exclude a particular commit type, I suggest using a conditional in the template, e.g.

```
{% for type_, commits in context.history.unreleased | dictsort %}
{% if type_ != "chore" %}
...
{% endif %}
{% endfor %}
```

Does that work for you?

**Comment by sbates** [comment]
Can I piggy back on this question? I feel like I have a similar one and it might be useful to have it here. Is there a way to ONLY update the changelog file with the PR for the merge to main instead of all the commits leading up to it? Our PR titles all have the <changetype>: format.

**Comment by bernardcooke53** [comment]
Hey @sbates - I have done this in the past working with a team, where we ensured that every PR we merged was done with "squash and merge" - that ensures the PR title goes into the resulting commit on main, and all the other commit messages are condensed into the body of that single commit. It's built-in GitHub functionality in the UI, but it's (almost definitely) just a rebase in the backend followed by a merge.

The downside is you lose the individual commits from the other branch, which you wouldn't do if it was a straight merge. I suggest that's the most import factor to consider - outside of the GitHub UI niceness (putting your PR title into a commit) I don't know of another way you could do this. PRs aren't really part of "git history" so there'd be no information to pick out and include in a changelog.

**Comment by sbates** [comment]
I'm taking a closer look and we have been using squash and merge which
leaves the changelog entry empty unless it's a feature. Maybe it's a
different problem than what I thought it was? It's a private repo but we're
going to make it public soon enough so I'm not worried about sharing.
## v0.2.0 (2023-04-06)
### Feature
* STFT-076: Secureli ignore - ability to suppress issues - auto prompt user
([#18](https://github.com/slalombuild/secureli/issues/18)) ([`c0178d3`](
https://github.com/slalombuild/secureli/commit/c0178d3daaaa7f1f00f5ef595b25a1233d76bf2a
))
## v0.1.6 (2023-04-05)


## v0.1.5 (2023-04-05)


## v0.1.4 (2023-04-05)


## v0.1.3 (2023-04-05)
