### ISSUE TITLE
Always getting "Current version 0.1.0 and current release version 0.0.0 do not match!"

### ISSUE THREAD

**Issue by rosaLux161** [python-semantic-release/python-semantic-release#567]
I'm always getting `Current version 0.1.0 and current release version 0.0.0 do not match!` while creating a new project. I've got rid of this by setting version_source to tags for the first release and switching back to commit, but I don't get the problem. Of course, before first run and checking the commit there is no initial version number, but it should be created instead of printing a none match with 0.0.0.

My pyproject.toml:

```
[tool.poetry]
...
version = "0.1.0"

...

[tool.semantic_release]
version_variable = [
    "project/__init__.py:__version__",
    "pyproject.toml:version"
]

hvcs = "gitlab"
repository_name = "xxx"
repository = "xxx"
branch = "main"
upload_to_pypi = true
upload_to_release = false
upload_to_repository = true
build_command = "pip install poetry && poetry build"
commit_version_number = true
commit_subject = "doc: Changelog {version}"
version_source = "commit"

```

my project/__init__.py:

```
__version__ = '0.1.0'

```

The debug output:

```
$ semantic-release publish --verbosity=DEBUG
debug: get_current_version_by_config_file()
debug: Parsing current version: path=PosixPath('project/__init__.py') pattern='__version__ *[:=] *["\\\'](\\d+\\.\\d+\\.\\d+(-beta\\.\\d+)?)["\\\']' num_matches=1
debug: Parsing current version: path=PosixPath('pyproject.toml') pattern='version *[:=] *["\\\'](\\d+\\.\\d+\\.\\d+(-beta\\.\\d+)?)["\\\']' num_matches=1
debug: Regex matched version: 0.1.0
debug: get_current_version_by_config_file -> 0.1.0
debug: get_current_release_version_by_commits()
debug: Checking commit 9d15fbb174899a7d8adb57af5b0c83cb454d6111
debug: get_current_release_version_by_commits -> 0.0.0
Current version: 0.1.0, Current release version: 0.0.0
debug: evaluate_version_bump('0.0.0', None)
debug: Reference v0.0.0 does not exist, considering entire history
debug: parse_commit_message('chore: Initial commit')
debug: parse_commit_message -> ParsedCommit(bump=0, type='chore', scope=None, descriptions=['Initial commit'], breaking_descriptions=[])
debug: Commits found since last release: 1
debug: get_new_version('0.1.0', '0.0.0', None, False, True)
error: Error: Current version 0.1.0 and current release version 0.0.0 do not match!
```

**Comment by bernardcooke53** [comment]
Hey @rosaLux161 :wave: 

Thanks for reporting this - I agree it's quite frustrating, I've hit the same issue myself! Though you can also fix it by setting the version in `pyproject.toml` to `0.0.0` if memory serves.

This is one of the things that the upcoming major version should address :slightly_smiling_face:

**Comment by r115** [comment]
I have a related problem from a different perspective though.

In my use case the repo has a lot of auto-commits coming in from other events. What I noticed is that only 52 (very odd number) commits were being considered to provide the current version. The last release commit was done much earlier.

I created a fake commit with the version number that I wanted and then made an actual release commit afterwards.

It just worked.

Hoping to help someone who gets unstuck.

**Comment by vali19th** [comment]
I have the same issue happening on new versions. v7.29.0 works fine 

Some other info that might be relevant: 
1. I tried with and without `.semver` and `release.config.yml`. 
2. My package is a namespace package
3. My package was released on pypi before I started using python-semantic-release

**Comment by anton-slashm** [comment]
Downgrading to `7.28.1` fixed it for me. Even `7.29.0` was behaving wildly.

**Comment by roggervalf** [comment]
Same issue from my side with version **7.34.3**. Following above suggestion worked for me.

**Comment by jseiser** [comment]
We have this problem in one of our repo's.

When i run this locally

```
debug: Commits found since last release: 143
debug: evaluate_version_bump -> minor
debug: get_new_version('3.0.0', '3.0.0', 'minor', False, True)
debug: get_new_version -> 3.1.0
warning: No operation mode. Should have bumped from 3.0.0 to 3.1.0
```

But when its being ran in the gitlab pipeline

```
debug: Commits found since last release: 39
debug: evaluate_version_bump -> minor
debug: get_new_version('3.0.0', '0.0.0', 'minor', False, True)
error: Error: Current version 3.0.0 and current release version 0.0.0 do not match!
```

I assume the fact its shows a different amount of commits is the issue.

**Comment by willdjennings** [comment]
This happened to my team. The problem for us seems to have been a single squashed commit in the `main` branch commit history. The solution that worked for us was to amend that commit message using `git reset` and `git push --force`.
