### ISSUE TITLE
Allow specifying which pyproject.toml to read config from

### ISSUE THREAD

**Issue by rustybrooks** [python-semantic-release/python-semantic-release#572]
## Description

Currently pyproject.toml is read from the current working directory.  There are some cases where you might want to manually specify the location of pyproject.toml.  `black` and `ruff` support this via the --config argument, `mypy` supports it via the --config-file parameter

## Use cases

My personal use case is, we have a library that packages a noxfile and a pyproject.toml, that contains a standard set of operations we want to use in all our repos.  A repo can add this package to their requirements and run a script contained in it, which will call nox.  noxfile.py is set up so that the nox sessions will use the package pyproject.toml for config, so that every project gets the same config for black, ruff, mypy, etc.

## Possible implementation

Just a simple command line parameter that overrides the default location of the config file.

**Comment by bernardcooke53** [comment]
Hey @rustybrooks - this is part of the upcoming v8 :+1:
