### ISSUE TITLE
Installing semantic-release

### ISSUE THREAD

**Issue by MalshaDeZ** [python-semantic-release/python-semantic-release#573]
I'm ultra new to python programming, so forgive me if this a stupid question, I can't seem to figure this one out. 
I'm trying to release a python library and following [this](https://py-pkgs.org/07-releasing-versioning) . I've done everything on the dot, installed using this command poetry add --dev python-semantic-release.
My `pip list` looks like this

`semantic-release              0.1.0`
`semantic-version              2.10.0`

and when I try to check the version it gives me the following error

`(base) C:\Users\userdz\projects\ABC\abc-sdk\abcclient>semantic-release --version
Traceback (most recent call last):
  File "C:\Users\userdz\AppData\Local\anaconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\userdz\AppData\Local\anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\userdz\AppData\Local\anaconda3\Scripts\semantic-release.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'semantic_release.cli'`

I've tried `pip install --upgrade --force-reinstall semantic-release[cli]`, but it doesn't do much help. There is always something missing

Any help in how to approach this would be much appreciated.

**Comment by bernardcooke53** [comment]
Hi @MalshaDeZ :wave: !

I think you might have installed the wrong package by mistake - please could you try adding `python-semantic-release` instead of `semantic-release` and trying again?

`pip install --upgrade --force-reinstall python-semantic-release`
