### ISSUE TITLE
Why is our semantic release not updating the changelog?

### ISSUE THREAD

**Issue by Lash-L** [python-semantic-release/python-semantic-release#575]
This is the project: https://github.com/humbertogontijo/python-roborock

We added semantic release after it was created
 
Heres our pyproject: https://github.com/humbertogontijo/python-roborock/blob/main/pyproject.toml

And here's our ci to run semantic release: https://github.com/humbertogontijo/python-roborock/blob/63267e7835ce1a86e402135d61c789ae639e3c82/.github/workflows/ci.yml#L50

Any advice would be appreciated!

**Comment by bernardcooke53** [comment]
Hey @Lash-L :wave: 

Thanks for the project links - really helpful (and looks cool!). I think you need to set `commit_version_number = True` in your configuration, you're not getting an updates to your [version](https://github.com/humbertogontijo/python-roborock/blob/33779655cc71c31c250e2e7d3d598d63975d4983/pyproject.toml#L3) in the metadata either :crossed_fingers:

**Comment by Lash-L** [comment]
That worked! Thanks @bernardcooke53
