### ISSUE TITLE
Question: Is it possible to only parse versions from tags based on a version prefix?

### ISSUE THREAD

**Issue by andrewcstewart** [python-semantic-release/python-semantic-release#576]
Let's say I have a monorepo with multiple projects where tags have the format `{project}-v{version}`.  Is it possible for PSR to only parse the previous tags that have a specified `{project}` tag prefix?

If I understand correctly, `tag_format` only specifies the format of the version string at the time of creating _new_ tags?

**Comment by bernardcooke53** [comment]
Hi @andrewcstewart :wave: 

Your understanding of the `tag_format` option is correct.
I have seen a couple of attempts at doing this - e.g. via storing a separate `pyproject.toml` in each project subdirectory with the different configuration in each, and then `cd`-ing during the workflow to release each project. That works ok, except that the commits are parsed from the repo as a whole, meaning a feature scoped to one project would register as a feature in every project.

There's also a [PR](https://github.com/python-semantic-release/python-semantic-release/pull/509) which is another interim solution, but it needs some tests adding. Monorepo support is still an open discussion.

**Comment by andrewcstewart** [comment]
Thanks for the info @bernardcooke53 - Do you think the idea of a `tag-prefix-filter` would make for a good feature request?

**Comment by andrewcstewart** [comment]
Also, apologies if this is a naive question - but why do we have to parse the git tags to get the next version number at all?  Why can't that just be parsed from the `pyproject.toml` and/or other files where the new version numbers will be written to?

**Comment by andrewcstewart** [comment]
@bernardcooke53 sorry for multiple replies, but digging through the code here I think this could be a pretty simple feature to enable monorepos.  I created a feature request: https://github.com/python-semantic-release/python-semantic-release/issues/579

I have the motivation and hopefully the time soon to draft a PR.  Would welcome any implementation thoughts / guidelines.

I'll close this question as answered too.
