### ISSUE TITLE
Stuck in commit_new_version stage

### ISSUE THREAD

**Issue by peeyushpashine** [python-semantic-release/python-semantic-release#578]
## The problem

This is happening with both .pre-commit-config.yaml local repo hook as well as manually providing semantic-release version command. I see the version bump happens with commit message  "feat: add new feature in the file as change comment". However it seems to be stuck, shell terminal does not come back at all. If I change "version_source" to commit, it keeps incrementing minor_version indifinitely. 

I am using python-semantic-release 7.33.2 version. Tried with older versions and facing same issue. I might be doing something wrong, please help here.

## Expected behavior

Minor Version bump and stops the process.

## Additional context

This is the verbose log for semantic-release version command

debug: get_current_version_by_tag()
debug: get_last_version(, pattern='(\d+\.\d+\.\d+(-beta\.\d+)?)')
debug: get_last_version -> 0.2.1
debug: get_current_version_by_tag -> 0.2.1
debug: get_current_release_version_by_tag()
debug: get_last_version(, pattern='v?(\d+\.\d+\.\d+(?!.*-beta\.\d+))')
debug: get_last_version -> 0.2.1
debug: get_current_release_version_by_tag -> 0.2.1
Current version: 0.2.1, Current release version: 0.2.1
debug: evaluate_version_bump('0.2.1', None)
debug: parse_commit_message('test commit')
debug: Ignoring UnknownCommitMessageStyleError: Unable to parse the given commit message: test commit
debug: parse_commit_message('feat: add and change files to test to check')
debug: parse_commit_message -> ParsedCommit(bump=2, type='feature', scope=None, descriptions=['add and change files to test to check'], breaking_descriptions=[])
debug: Commits found since last release: 2
debug: evaluate_version_bump -> minor
debug: get_new_version('0.2.1', '0.2.1', 'minor', False, True)
debug: get_new_version -> 0.3.0
debug: get_repository_owner_and_name()
debug: get_repository_owner_and_name -> ('dummy', 'dummy')
debug: Running publish on branch main
debug: checkout(main)
debug: checkout -> M    setup.py
debug: A        temp.py
debug: Your branch is up to date with 'origin/main'.
debug: generate_changelog('0.2.1')
debug: parse_commit_message('test commit')
debug: Ignoring UnknownCommitMessageStyleError: Unable to parse the given commit message: test commit
debug: parse_commit_message('feat: add and change files to test to check')
debug: parse_commit_message -> ParsedCommit(bump=2, type='feature', scope=None, descriptions=['add and change files to test to check'], breaking_descriptions=[])
debug: Creating new changelog section for feature 
debug: generate_changelog -> {'breaking': [], 'feature': [('', 'Add and change files to test to check')]}
debug: markdown_changelog('dummy', 'dummy', '0.3.0', {'breaking': [], 'feature': [('', 'Add and change files to test to check')]}, header=False, previous_version='0.2.1')
debug: markdown_changelog -> ### Feature
debug: * Add and change files to test to check
debug: update_changelog_file('0.3.0', '### Feature
debug: * Add and change files to test to check 
warning: Changelog file not found: /Users/dummy/Documents/dummy/CHANGELOG.md - creating it.
debug: update_additional_files()
Bumping with a minor version to 0.3.0
debug: set_new_version('0.3.0')
debug: Writing new version number: path=PosixPath('setup.py') pattern='__version__ *[:=] *["\\\'](\\d+\\.\\d+\\.\\d+(-beta\\.\\d+)?)["\\\']' num_matches=0
debug: set_new_version -> True
debug: commit_new_version('0.3.0')

It is stuck here forever.

**Comment by peeyushpashine** [comment]
@bernardcooke53 It seems to be stuck before that. Files are not modified. I dont see the files being popped up to "Staged changes -> Changes" in my Git IDE.

**Comment by bernardcooke53** [comment]
I wonder if it might be that none of your files are being modified - it seems like your configuration is indicating the version is in `setup.py` but not being found.

Can you add your configuration please? And (if possible) `setup.py` contents?

**Comment by peeyushpashine** [comment]
This is how my setup.py looks:

# setup.py
# Setup installation for the application
# version control test 6
from os.path import abspath, dirname, join
from pathlib import Path

import toml
from setuptools import find_namespace_packages, setup

BASE_DIR = Path(__file__).parent
# __version__ = "0.3.0"
version = '0.7.0'
# pyproject_path = join(dirname(abspath("__file__")), "pyproject.toml")

# file = open(pyproject_path)
# toml_str = file.read()
# parsed_toml = toml.loads(toml_str)

# Load packages from requirements.txt
with open(Path(BASE_DIR, "requirements.txt")) as file:
    required_packages = [ln.strip() for ln in file.readlines()]

test_packages = [
    "pytest==6.0.2",
    "pytest-cov==2.10.1",
]

dev_packages = [
    "black==20.8b1",
    "flake8==3.8.3",
    "isort==5.5.3",
    "jupyterlab==2.2.8",
    "pre-commit",
]

docs_packages = [
    "mkdocs==1.1.2",
    "mkdocs-macros-plugin==0.6.0",
    "mkdocs-material==6.2.4",
    "mkdocstrings==0.14.0",
]

setup(
    name="dummy",
    version=version,
    # version=parsed_toml["tool"]["commitizen"]["version"],
    license="MIT",
    description="",
    author="",
    keywords=[
        "machine-learning",
        "artificial-intelligence",
        "anamoly detection",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Topic :: Software Development :: Build Tools",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.7",
    ],
    python_requires=">=3.7,<3.8",
    packages=find_namespace_packages(),
    package_data={
        "": ["*.json", "*.yaml"],
    },
    install_requires=[required_packages],
    include_package_data=True,
    extras_require={
        "test": test_packages,
        "dev": test_packages + dev_packages + docs_packages,
        "docs": docs_packages,
    },
 
)
@bernardcooke53

**Comment by bernardcooke53** [comment]
Based on the logs and your `setup.py` I think the setting for `version_variable` is wrong - I guess it's set to this:

```
version_variable = __version__ *[:=] *"\'["\']
```

The underscores and missing `.*` mean the regex won't match because your version variable is just `version`, not `__version__`.

Try setting it to:

```
version_variable = version *[:=] *["\'].*["\']
```
