### ISSUE TITLE
Version from Github Tag in Jenkins

### ISSUE THREAD

**Issue by Robmosh91** [python-semantic-release/python-semantic-release#580]
Hey Folks,

I'm using python-semantic-release to get versioning done for a python package published to an internal pypi repository.
Package is published from main if a (release) tag is given from Jenkins.
For now I got everything running and python-semantic-versioning is counting the version, but I have 2 issues with it which I couldn't solve and couldn't find resolutions in the documentation.

1. Use tag as a version without dev... appendix
2. Do not add a count to the version but use the version provided in the tag.

Right now, when the tag is set to v0.0.2, instead of using this, what is used is 0.0.3.dev0+gc... 

Anybody has a tip for me how to solve this?

**Comment by bernardcooke53** [comment]
Hey @Robmosh91 :wave:

I have seen this, admittedly a long time ago - and I can't remember if it was using PSR or the node version. It was happening when I merged a PR, and none of the commits were conventional (e.g. if I hit the button the merge a PR and the title was set by the GitHub UI).

For me it was just making sure that the main branch has at least one conventional commit on it after a merge
