### ISSUE TITLE
Original (NPM) Semantic release vs. Python Semantic release

### ISSUE THREAD

**Issue by MichalVasut** [python-semantic-release/python-semantic-release#586]
We are currently deciding, what tools to select for our python based backend that would take care of versioning and changelog. Semantic release is my personal favorite
- it's Swiss knife (all in one solution)
- our frontend team uses original / npm semantic release

But there is still difference - I don't mean less features, but even the architecture is entirely different and I wonder, why?

Based on the docs:
> Automatic Semantic Versioning for Python projects. This is a Python implementation of [semantic-release](https://github.com/semantic-release/semantic-release) for JS by Stephan Bönnemann.

I would assume that you would try to keep the architecture and plugin based system that is in original, but that's not the case and I wonder why?

- not enough time time and / or people to keep up with the JS version?
- you've taken the idea and reimplemented it by yourself (== decision made at the beginning), because... (feel free to tell the reasons).

Original solution is imho more flexible and also easier to maintain, when broken to smaller parts (plugins). 

Thanks for answer.

Michal

**Comment by bernardcooke53** [comment]
Hi @MichalVasut :wave: 

I know when you're choosing tooling you generally need to "get moving" with something - apologies for taking a while to come back to you, I'm just catching up on issues/PRs now.

I agree with what you've touched on above - Python Semantic Release is undoubtedly a smaller project than the original NPM version - the Github stars alone are a pretty clear indication, ~500 for PSR vs 17k for NPM.

I have hit one specific irritation with the NPM version, namely that (last time I used it) it restricted you to just three "release channels". While this might be a key part of the node ecosystem, I find that's imposing an unnecessary restriction on projects using other languages. For a lot of people that may be a minor complaint, but for example when using a shared dev environment I've wanted to publish a build containing the Git branch name to run a set of tests against shared infrastructure (data engineering/database-kind of work, for example).

The other thing is more human - I've worked on a lot of Python projects and ideally I'd like to avoid introducing the node ecosystem as just _one more thing_ that the team needs at least a surface-level understanding of.

That said, in its current state, Python Semantic Release only supports releases from a single branch, which is a deal-breaker for some workflows - that's one of the major features I'm looking at as part of the next major release. 

If you look at other popular tools such as `ansible`, `poetry`, `pytest`, or even the original `semantic-release` - you can see the advantages of creating a plugin ecosystem around a core entrypoint. I think eventually this project will go in the same direction, there's certainly appetite for it (#321, [etc](https://github.com/python-semantic-release/python-semantic-release/issues/487#issuecomment-1232748499)). There's a fair bit of stuff that needs to happen before that, though, so it's definitely a long-term idea. Supporting a plugin ecosystem has benefits in terms of federating maintenance, but there's always tradeoffs (ensuring a good developer experience for plugin authors, documentation, etc).

Every company is different but it sounds like you've got a good case for choosing the original, node `semantic-release`:

* You've already got engineers using it in production, whose experience you can lean on
* Any DevOps/security engineers should have already vetted it - one less tool to keep track of

Equally, if you're working on something relatively simple, you could use Python Semantic Release for:

* Integrating with an existing Python/package repository/build system setup
* Cleaner configuration that lives alongside the rest of your project metadata

Hope this helps you get off the ground! :rocket:

**Comment by MichalVasut** [comment]
@bernardcooke53 first of all, don't apologize, it's minor thing with tons of alternatives. 😊

Your assessment is correct - I've chosen the original Semantic Release, exactly because of this - it's ready to use & proven solution.

The reason why I was looking for python only solution is exactly that you've mentioned - we (BE team) didn't want to mix Node into python environment. But at the end, it will be only small stage in GitlabCI, that will use Node docker image, so no biggie. 😊
