### ISSUE TITLE
Potential feature for CICD and local testing: 'dry-run'

### ISSUE THREAD

**Issue by Gazzzzyy** [python-semantic-release/python-semantic-release#588]
## Description

It would be nice if there was a parameter that could be used to test if the semantic release procedure will run in the current build. Similar to pips now deprecated `pip install x  --no-install` or `poetry build --dry-run`

## Use cases

With the latest patch, I ran into an issue with the releasing procedure  (#584). With this feature, we could get our devs to add this to their local checks & tests before releasing. The release procedure (in our company at least) is that semantic-release must be triggered after a merge to main. If there is a failure, like we ran into, then we have to set up and create a new pull-request. This also means that there are changes in main that are not tagged with the latest release, until we manually go back and force the release.

## Possible implementation

Something like
`semantic-release publish --dry-run`.

**Comment by bernardcooke53** [comment]
Hi @Gazzzzyy - this is a great suggestion, going into the next major release (which you can try out if you like - `pip install --pre  python-semantic-release>=8.0.0`)

**Comment by Gazzzzyy** [comment]
Sorry for the late reply, it's been a hectic few weeks!! Thanks for the reply, and I wasn't aware of the `--noop` param. I'll be sure to give it a whirl!
