### ISSUE TITLE
Support PyPI's new Trusted Publishers

### ISSUE THREAD

**Issue by MicaelJarniac** [python-semantic-release/python-semantic-release#589]
## Description

https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/

PyPI now supports uploading from a GitHub Action without needing tokens.

**Comment by bernardcooke53** [comment]
Hey @MicaelJarniac :wave: 

I didn't know this was coming out but it looks really cool!

We probably won't do this, however - Python Semantic Release will [drop publishing to package repositories](https://github.com/python-semantic-release/python-semantic-release/issues/487#issuecomment-1448874667) from its next major version. The TL;DR is we're basically re-exporting `twine` functionality, so we're going to stop doing that and recommend how to replace the functionality with `twine` and/or `pypa/gh-action-pypi-publish` instead :+1:
