### ISSUE TITLE
GITLAB_CI variable does not seem to be caught

### ISSUE THREAD

**Issue by rasmus91** [python-semantic-release/python-semantic-release#595]
## The problem

I have a project where I have setup python-semantic-release as the last job in the pipeline. It works fine(ish) until it has to create the release, at which point I get this:

```bash
debug: upload -> True
debug: get_hvcs()
debug: get_hvcs -> <class 'semantic_release.hvcs.Github'>
warning: Missing token: cannot post changelog to HVCS
debug: get_hvcs()
debug: get_hvcs -> <class 'semantic_release.hvcs.Github'>
warning: Missing token: cannot upload to HVCS
Removing distribution files
debug: Removing build folder: `dist`
Publish has finished
```

## Expected behavior

Well since the release job looks like this:

```yaml
Release:
  variables:
    GITLAB_CI: 'true'
  ...
```

I would expect it to load something like: `semantic_release.hvcs.Gitlab` instead.

But it has infact ignored that at all times, and the only way I have been able to do tagging etc. has been by doing this as well

`git remote set-url origin https://root:$GITLAB_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git`

(GITLAB_TOKEN is a group level access token, but before that I tried with a full access personal token in  the env vars as suggested, and it just did not work, as it kept loading the Github hvcs class)

## Additional context

So I have managed to get every other part of this working, except for the actual creation of a release on the gitlab releases page.

This is on a selfhosted gitlab instance

**Comment by bernardcooke53** [comment]
Hey @rasmus91 - could you please share your configuration?

To avoid confusion - it looks as though in your job, PSR is identifying and verifying the `GITLAB_CI` variable is set, but this doesn't change how PSR sets its `hvcs` class. You need to set the [`hvcs=gitlab`](https://github.com/python-semantic-release/python-semantic-release/blob/222a443dfd6f129884c161d5e1821571e80dcb0b/semantic_release/defaults.cfg#L26) option in your configuration.
