### ISSUE TITLE
8.0.0a6 inconsistent behavior for `print_only` when no release should be made

### ISSUE THREAD

**Issue by smeng9** [python-semantic-release/python-semantic-release#599]
*Please describe your problem. Include links to any relevant pages or files.*

I have found some inconsistent behavior

In documentation:
https://github.com/python-semantic-release/python-semantic-release/blob/8.0.x/docs/commands.rst#--print

> Note that instead of printing nothing at all, if no release will be made, the current version is printed.

In code:
https://github.com/python-semantic-release/python-semantic-release/blob/8.0.x/semantic_release/cli/commands/version.py#L287

> If the new version has already been released, we fail and abort

And no version will be printed.

**Comment by bernardcooke53** [comment]
I added the `--strict` which should make this behaviour explicit - I remember being on the fence about how strict to be, after you raised this I realised it would be nice to be able to choose. Should no longer be an issue, use `semantic-release version` if you want a graceful exit, and `semantic-release --strict version` if you want an error. Thanks for pointing it out :pray:
