### ISSUE TITLE
Inconsistent logic when passing CLI parameters via -D

### ISSUE THREAD

**Issue by lpfann** [python-semantic-release/python-semantic-release#600]
## The problem

The issue is that the -D options in the CLI sometimes rely on the actual string `false` (like build_command). And others rely on the actual boolean True/False.
This leads to confusion and unexpected behaviour.

This is a combination needed for us to disable uploads which shows the issue:
```
  -D upload_to_release=False \
  -D upload_to_repository=False \
  -D upload_to_pypi=False \
  -D build_command=false \
```

It took a while to get this combination. Its an issue that the string `false` is interpreted as True for the `upload_...` options.

## Expected behavior

The CLI should be robust and parse `true/false` as booleans instead of interpreting `false` as boolean True.
Also build_command should allow False.

**Comment by smeng9** [comment]
I think this duplicate of https://github.com/python-semantic-release/python-semantic-release/issues/389

**Comment by codejedi365** [comment]
Obsolete as of `v8`, the `--define` option was deprecated.
