### ISSUE TITLE
8.0.0a7 Inconsistent types of assets with pydantic

### ISSUE THREAD

**Issue by smeng9** [python-semantic-release/python-semantic-release#602]
## The problem

The types for assets are not consistent and users cannot upload assets to vcs

## Expected behavior

The types for assets in config should be consistent

## Additional context

In [configurations.rst](https://github.com/python-semantic-release/python-semantic-release/blob/8.0.x/docs/configuration.rst#assets-liststr) assets is List[str]

In [config.py](https://github.com/python-semantic-release/python-semantic-release/blob/8.0.x/semantic_release/cli/config.py#L129) assets is Tuple[str, ...]

In [version.py](https://github.com/python-semantic-release/python-semantic-release/blob/8.0.x/semantic_release/cli/commands/version.py#L319) It is trying to concat tuple to a list which causes an exception.

**Comment by bernardcooke53** [comment]
Closed by #603
