### ISSUE TITLE
action fails since bookworm release

### ISSUE THREAD

**Issue by SvenStaehs** [python-semantic-release/python-semantic-release#606]
## The problem

using the action, github first builds the Dockerfile, which references python:3.10 without any mention which version of debian to use. Debian 12 bookworm has been released recently, and a python:3.10-bookworm published, which is now used.
But the Dockerfile then tries to install git from bullseye-backports, which would downgrade the git package, resulting in the following errors, probably for every single user out there (unless there's some caching going on):

> E: Packages were downgraded and -y was used without --allow-downgrades.
> ERROR: failed to solve: process "/bin/sh -c echo \"deb http://deb.debian.org/debian bullseye-backports main\" >> /etc/apt/sources.list;     apt-get update;    apt-get install -y git/bullseye-backports" did not complete successfully: exit code: 100

## Expected behavior

action should work 

## Additional context

proposed fix for now is to specify the version of debian to use by pinning to python:3.10-bullseye as base image.
Long-term you'll want to adopt python:3.11-bookworm, but that's a completely different matter.

**Comment by bernardcooke53** [comment]
Thank you for spotting this @SvenStaehs , I will make a PR later today when at my computer unless someone can get to it first 👍

**Comment by SvenStaehs** [comment]
> Thank you for spotting this @SvenStaehs , I will make a PR later today when at my computer unless someone can get to it first 👍

Thanks, I already made one, just have to merge it 😉 #605

**Comment by bernardcooke53** [comment]
Didn't see whoops 😂 commitlint failed with the same issue... it's gonna be a good day at the office
