### ISSUE TITLE
bug: docker image cannot be build on github actions runner

### ISSUE THREAD

**Issue by MartinBernstorff** [python-semantic-release/python-semantic-release#607]
Thanks a ton for your hard work!

## The problem

See log here: https://github.com/Aarhus-Psychiatry-Research/timeseriesflattener/actions/runs/5276922524/jobs/9544498783

Specifically, 

```bash
Recommended packages:
    less
  The following packages will be DOWNGRADED:
    git
  0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 0 not upgraded.
  E: Packages were downgraded and -y was used without --allow-downgrades.
```

## Expected behavior

The action can build the docker image.

Let me know if I can be of any help :-)

**Comment by bernardcooke53** [comment]
Hey @MartinBernstorff - this was just fixed this morning, try bumping the Action version to v7.34.4 🤞
