### ISSUE TITLE
Help needed with setup in gitlab cicd

### ISSUE THREAD

**Issue by BastLast** [python-semantic-release/python-semantic-release#610]
Hi ! I am having some issues with the setup in a gitlab pipeline here is the setup i have :

release-pypi:
  stage: release
  image:
    name: python:3.10.0
    entrypoint: ['']
  tags:
    - docker
  script:
    - python -m pip --no-cache-dir install poetry
    - poetry install
    - git tag -d $(git tag -l)
    - git fetch --tags
    - git config --global user.email $GIT_AUTHOR_EMAIL
    - git config --global user.name $GIT_AUTHOR
    - git remote set-url origin https://$GIT_AUTHOR:$GL_TOKEN@nameoftherepositoryongitlab
    - poetry run semantic-release publish --verbosity=DEBUG
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    
   I believe the config with the remote set and user is not necessary but i could not understand how it is supposed to be setup.
   
  this setup do not get a 403 but the commits links in the changelog are pointing to github.com instead of gitlab. I saw docs that speaks about hcvs that has to be set to gitlab but is it in the gitlab variables or in the pipeline variables ?

**Comment by bernardcooke53** [comment]
Hi @BastLast - could you please show your `python-semantic-release` configuration? You need to set `hvcs = "gitlab"` in your configuration file.

**Comment by BastLast** [comment]
it seems i do not have a configuration file in this repository, 

Here is the parameters i have in my toml project :
[tool.semantic_release]
version_variable = "swa/version.py:__version__"
version_toml = "pyproject.toml:tool.poetry.version"
branch = "release-2.x"
build_command = "poetry build"
changelog_scope = false
tag_format = "release-{version}"
commit_message = "chore(release): {version} (automated release)"
hcvs = "gitlab"
repository_url =  "artifactory url"

**Comment by bernardcooke53** [comment]
Hi @BastLast - I think you have a typo, `hcvs` instead of `hvcs` - can you try that?

**Comment by BastLast** [comment]
> Hi @BastLast - I think you have a typo, `hcvs` instead of `hvcs` - can you try that?

Yup saw that litteraly two hours ago will try soon and update here !

**Comment by BastLast** [comment]
this was indeed one of my issue, I have a few other things i want to ask but no time to work on it, im closing this and will reopen an issue later if needed :) thx for the answer 👍
