### ISSUE TITLE
Why am I getting the error "'semantic_release' is a package and cannot be directly executed"?

### ISSUE THREAD

**Issue by eyomi-gilead** [python-semantic-release/python-semantic-release#615]
I am using sematic-release in my Github Actions workflow. I have it configured to run using the Github Action as illustrated below:
```
...
      - name: Python Semantic Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: python-semantic-release/python-semantic-release@v7.34.6
...

```
When the pipeline runs, I get the following error:
`/semantic-release/.venv/bin/python: No module named semantic_release.__main__; 'semantic_release' is a package and cannot be directly executed`

I also get the following in my workflow output:
` DEPRECATION: python-semantic-release is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559`
Any idea why and what do I need to do resolve it?

**Comment by bernardcooke53** [comment]
Hi @eyomi-gilead - not sure why this is erroring out from just that snippet, are you able to link your full workflow definition and/or a link to the action?
