### ISSUE TITLE
Pydantic Validation Error with `version_toml` in 8.0.0

### ISSUE THREAD

**Issue by wizrds** [python-semantic-release/python-semantic-release#624]
## The problem

Beginning in version 8.0.0 I am receiving the following traceback:

```
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for RawConfig
version_toml
  value is not a valid tuple (type=type_error.tuple)
```

## Expected behavior

It should correctly bump the version.

## Environment

python: **3.11.2**
pip: **22.3.1**
python-semantic-release: **8.0.0**

## Configuration

```
[tool.semantic_release]
version_toml = "pyproject.toml:tool.poetry.version"
```

## Logs

Please provide debug logs for the command you are using with the `-vv` flag, e.g.

```shell
[14:02:49] DEBUG    [semantic_release.cli.commands.main] DEBUG main.main: logging level set to: DEBUG                                                                               main.py:106
           DEBUG    [semantic_release.cli.commands.main] DEBUG main.main: global cli options: GlobalCommandLineOptions(noop=False, verbosity=2, config_file='pyproject.toml',       main.py:124
                    strict=False)                                                                                                                                                              
           INFO     [semantic_release.cli.commands.main] INFO main.main: Loading TOML configuration from pyproject.toml
           <TRACEBACK>
```

Rolling back to 7.34.6 fixes the issue.

**Comment by bernardcooke53** [comment]
Hey @wizrds - `version_toml` should be a list, try wrapping that value in `[]`

**Comment by wizrds** [comment]
Ah I see, so not being a list was the bug then?

**Comment by bernardcooke53** [comment]
Yes, `version_toml` is a list in v8

**Comment by css-optivoy** [comment]
The fact that `version_toml` is now required to be a list in `pyproject.toml` could probably be better documented in [the doc](https://python-semantic-release.readthedocs.io/en/latest/configuration.html).

Currently it simply states that the value of `version_toml` can be something like `pyproject.toml:tool.poetry.version`.
The closest it gets to implying it must be a list is saying
> [`version_toml` is s]imilar to `version_variable` [...]

where the doc for `version_variable` in turn says:

> In pyproject.toml specifically, you **can** also use the TOML list syntax to specify multiple versions

(Emphasis mine.)

This makes it sounds like you **can** use **either** a list **or** a string for `version_variable`, and by extension, for `version_toml`.

**Comment by browniebroke** [comment]
> The fact that `version_toml` is now required to be a list in `pyproject.toml` could probably be better documented in [the doc](https://python-semantic-release.readthedocs.io/en/latest/configuration.html).

It is much better in [the source file of the docs ](https://github.com/python-semantic-release/python-semantic-release/blob/master/docs/configuration.rst#version_toml-liststr). Unfortunately [the docs are failing to build](https://github.com/python-semantic-release/python-semantic-release/issues/487#issuecomment-1637204443) right now.
