### ISSUE TITLE
TypeError: HEAD is a detached symbolic reference

### ISSUE THREAD

**Issue by DonFortes** [python-semantic-release/python-semantic-release#627]
## The problem

Every pipeline at every repository breaks with TypeError: HEAD is a detached symbolic reference as it points to SHA-1 commit value

## Expected behavior

Everything must work fine

## Environment

python:3.10.11
python_semantic_release-8.0.0

## Configuration
```
[tool.semantic_release]
branch = "dev"
build_command = false
hvcs = "gitlab"
upload_to_pypi = false
upload_to_repository = false
version_toml = ["pyproject.toml:tool.poetry.version"]
```
## Logs

pip install python-semantic-release
semantic-release publish -v DEBUG

```Traceback (most recent call last):
  File "/usr/local/bin/semantic-release", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line [107](/jobs/4666190584#L107)8, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1685, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/semantic_release/cli/commands/main.py", line 142, in main
    runtime = RuntimeContext.from_raw_config(
  File "/usr/local/lib/python3.10/site-packages/semantic_release/cli/config.py", line 282, in from_raw_config
    branch_config = cls.select_branch_options(raw.branches, repo.active_branch.name)
  File "/usr/local/lib/python3.10/site-packages/git/repo/base.py", line 896, in active_branch
    return self.head.reference
  File "/usr/local/lib/python3.10/site-packages/git/refs/symbolic.py", line 309, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to SHA-1 value
Cleaning up project directory and file based variables
```

**Comment by browniebroke** [comment]
I've got the same issue, and your explanation makes sense... But not the solution 😄 

More context on my use case, in case it's important: basically, on the branches which aren't the main one, [I run PSR with the `--noop` option](https://github.com/browniebroke/deezer-python/blob/767deb27d607fc5587bd75a3d199e1720a1d9663/.github/workflows/ci.yml#L54-L76) to check that the pull request hasn't broken the release.

As far as I can see, my workflow is following [the example from the docs](https://github.com/python-semantic-release/python-semantic-release/blob/master/docs/automatic-releases/github-actions.rst#example-workflow), and has a checkout step before:

```
- uses: actions/checkout@v3
   with:
     fetch-depth: 0
```

I've remove the fetch-depth argument but it doesn't help.

**Comment by bernardcooke53** [comment]
Ah okay I see - I resolved the same issue in this project [here](https://github.com/python-semantic-release/python-semantic-release/blob/9b6ddfef448f9de30fa2845034f76655d34a9912/.github/workflows/main.yml#L117). The TL;DR is the following:

```yaml
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
```

That achieves the same thing that `git checkout <the PR base branch>` would, but in GitHub Actions-land

I'll add it to the docs when I get a second :+1:

**Comment by DonFortes** [comment]
```
> In your pipeline, if you add `git checkout <the branch for the pipeline>` before invoking `python-semantic-release` this should be resolved 🤞
```
Thanks a lot!🙏This worked for me

**Comment by browniebroke** [comment]
That almost did the trick for me. Since I run the job on pull request, `github.ref_name ` is equal to something like `<pr number>/merge`. I fixed it as follows:


```yml
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}
```
