### ISSUE TITLE
Readthedocs PDF format not building

### ISSUE THREAD

**Issue by bernardcooke53** [python-semantic-release/python-semantic-release#630]
## The problem

The documentation for Python Semantic Release at https://python-semantic-release.readthedocs.io/en/latest/ is not updated for v8. The documentation build is currently failing.

## Expected behavior

Docs to be updated

## Environment

N/A

## Configuration

N/A

! LaTeX Error: Unknown graphics extension: .yml.
...
! LaTeX Error: Unknown graphics extension: .svg.
...
! Package inputenc Error: Unicode char 💥 (U+1F4A5)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
...

## Additional context

I'm seeing that [readthedocs](https://python-semantic-release.readthedocs.io/en/latest/) isn't updating with the docs for v8 - it looks like the [docs build](https://readthedocs.org/projects/python-semantic-release/builds/) has been failing for a while, for a time it was due to the Sphinx version in use but then the error changed after [this commit](https://github.com/python-semantic-release/python-semantic-release/commit/0c234475d27ad887b19170c82deb80293b3a95f1) to other errors.

## Workaround

While not ideal, you can either check the documentation directly in the source code of this repo, or you can clone & build the documentation locally to view in your web-browser:

```shell
git clone git@github.com:python-semantic-release/python-semantic-release.git
cd python-semantic-release
python3 -m venv .venv && source .venv/bin/activate
pip install -e ".[dev, test, docs, mypy]"
cd docs/
```
You can then build the docs with the following:
### Windows
```cmd
make.bat livehtml
```

### Mac/Linux
```bash
make livehtml
```

Open a new tab in the browser and go to `http://localhost:8000` to view the documentation.

Will close this when the docs build is working again.

**Comment by MicaelJarniac** [comment]
I've opened #631 to fix one of the problems with the new docs.

**Comment by bernardcooke53** [comment]
I've pushed up a change to the readthedocs config reducing the formats to just `htmlzip`, let's see if that gets something built

**Comment by bernardcooke53** [comment]
That suggestion worked @MicaelJarniac - thank you! Docs are updated now, no additional downloadable formats for the moment but I don't think that's a major concern

**Comment by MicaelJarniac** [comment]
That's great news! I'm poking around to see if I can figure something out.

**Comment by bernardcooke53** [comment]
Unpinned now the docs are out with the major version, I guess there'll be fewer people coming to the issues who'll need to know about just the missing formats
