### ISSUE TITLE
`semantic-release version --prerelease` does not force a prerelease version bump.

### ISSUE THREAD

**Issue by css-optivoy** [python-semantic-release/python-semantic-release#639]
## The problem

`semantic-release version --prerelease` does not force a prerelease version bump:

```
$ git log
commit 2f01c54100ae5a63020e267a397221f088f927e3 (HEAD -> bump)
Author: css
Date:   Tue Jul 18 10:04:41 2023 +0200

    build(meh): Blah

commit bfed5b9fda67e7ef3e251c18860f48b59798b7a8 (tag: 0.27.7-dev.3)
Author: semantic-release <semantic-release>
Date:   Mon Jul 17 11:33:02 2023 +0000

    0.27.7-dev.3
    
    Automatically generated by python-semantic-release

$ semantic-release version --prerelease
[...]
           WARNING  [semantic_release.cli.commands.version] WARNING version.version: Forcing prerelease due to '--prerelease' version.py:247
                    command-line flag     
           INFO     [semantic_release.version.algorithm] INFO algorithm.tags_and_versions: found 303 previous tags           algorithm.py:55
           INFO     [semantic_release.version.algorithm] INFO algorithm.next_version: Found 106 full releases (excluding    algorithm.py:245
                    prereleases)                                                                                                            
           INFO     [semantic_release.version.algorithm] INFO algorithm.next_version: The last full release was 0.27.6,     algorithm.py:267
                    tagged as '0.27.6'                                                                                                      
           INFO     [semantic_release.version.algorithm] INFO algorithm.bfs: found latest version in branch history:         algorithm.py:91
                    '0.27.6' (f5dbb72)                                                                                                      
           INFO     [semantic_release.version.algorithm] INFO algorithm._bfs_for_latest_version_in_history: the latest      algorithm.py:110
                    version in this branch's history is 0.27.6                                                                              
           INFO     [semantic_release.version.algorithm] INFO algorithm.next_version: The last full version in this         algorithm.py:291
                    branch's history was 0.27.6                                                                                             
           INFO     [semantic_release.version.algorithm] INFO algorithm.next_version: The type of the next release release  algorithm.py:368
                    is: no_release                                                                                                          
           INFO     [semantic_release.version.algorithm] INFO algorithm.next_version: No release will be made               algorithm.py:370
0.27.7-dev.3
           INFO     [semantic_release.version.algorithm] INFO algorithm.tags_and_versions: found 303 previous tags           algorithm.py:55
No release will be made, 0.27.7-dev.3 has already been released!
```

## Expected behavior

Running the above should produce a new prerelease version.

## Environment

```shell
$ semantic-release --version
semantic-release, version 8.0.1
```

## Additional context

From a quick glance at the code it looks like it might be the logic around here:
https://github.com/python-semantic-release/python-semantic-release/blob/2129b729837eccc41a33dbb49785a8a30ce6b187/semantic_release/cli/commands/version.py#L246-L271

Setting any of `--major`, `--minor` and `--patch` will set `force_level`, but setting `--prerelease` will set `force_prerelease`, which does not appear to set the `level_bump`.

Adding `force_level = "PRERELEASE_REVISION"` here, makes the logic work as expected:
https://github.com/python-semantic-release/python-semantic-release/blob/2129b729837eccc41a33dbb49785a8a30ce6b187/semantic_release/cli/commands/version.py#L246-L247

**Comment by bernardcooke53** [comment]
Hey @css-optivoy - The intention with `--prerelease` is to force the next version to be a prerelease _if there's one to be made_ - I can see you're getting "no release will be made" as output. What have you set for your `commit_parser_options`?

By default `commit_parser_options.patch_types = ["fix", "perf"]`, so because `"build"` isn't in there PSR thinks there's no commits since the last release that should trigger a new one - if you want `"build"` to trigger a patch release you'll need to add it to `commit_parser_options.patch_types`

**Comment by css-optivoy** [comment]
> The intention with `--prerelease` is to force the next version to be a prerelease _if there's one to be made_

Thank you for clarifying.

Unfortunately that is surprising because:

1) This appears to be new, breaking change behaviour in v8:
```
$ git log
commit 195afb360e7b6825a279abe431162ae5ec249c96
Author: css
Date:   Wed Jul 19 07:47:48 2023 +0200

    build(A): B

commit 578fe4dca303c14ca0357fd6d161c5b10e1397e5 (tag: 0.27.7-dev.4, origin/main, main)
Author: semantic-release <semantic-release>
Date:   Tue Jul 18 08:57:11 2023 +0000

    0.27.7-dev.4
    
    Automatically generated by python-semantic-release

$ poetry show python-semantic-release                         
 version      : 7.34.6  

$ semantic-release version --prerelease
Creating new version
Current version: 0.27.7-dev.4, Current release version: 0.27.6
Bumping with a patch version to 0.27.7-dev.5
```

2) That makes `--prerelease` special, and different from all the other level bumps, `--major`, `--minor`, `--patch`.
As seen in the code snippet above, the other flags _do_ force a version bump regardless, and `--prerelease` is the only one that doesn't. And this difference is not mentioned in any form in the help:

```
$ semantic-release --version
semantic-release, version 8.0.1
$ semantic-release version --help
[...]
Options:
  --prerelease                    Force the next version to be a prerelease
  --major                         force the next version to be a major release
  --minor                         force the next version to be a minor release
  --patch                         force the next version to be a patch release
```


We are currently relying on the old behaviour for all our repos, so I've unfortunately had to downgrade all of them to v7 when this started breaking everything.
Is there some way to get the old behaviour with v8?

I see `commit_parser_options.patch_types` might be a workaround of sorts. But it still doesn't completely solve it, as we specifically want to force _prerelease_ - even if there are no tags that match anything in particular.

**Comment by bernardcooke53** [comment]
Hi @css-optivoy 

I've had a re-read of the docs and the source code, I responded in a hurry to this yesterday which was probably a bad idea - something about the notion of "_if there's one to be made_" didn't sit right with me. 

It turns out that that would be really strange and inconsistent - and that's not how I wrote the code, nor how I documented it, and it's a bug/break because it _should_ be consistent.

I still think you need to add in those `patch_types`, but as you pointed out even in the help text - `--prerelease` _is_ a force.

I've raised #647 which should put these options straight - really what `--prerelease` is doing should be a new feature, `--as-prerelease`, and the `--prerelease` flag should force as it used to. I'd be grateful if you could have a glace over the PR

**Comment by css-optivoy** [comment]
Thank you.

> I'd be grateful if you could have a glace over the PR

I've left some thoughts on https://github.com/python-semantic-release/python-semantic-release/pull/647#issuecomment-1643364182

> I still think you need to add in those `patch_types`

A bit of an aside, but is there a `prerelease_types`? I couldn't seem to find an exhaustive list of options in the docs, and no mention of a `prerelease_types`.

I think what we'd want is essentially `commit_parser_options.prerelease_types = ["*"]`

**Comment by bernardcooke53** [comment]
Have responded on the PR - thanks for having a look.

To your aside - there's no `prerelease_types`, any `allowed_tag` is eligible to be made to a prerelease.
It would be possible to write a commit parser that always parses at least a prerelease revision, that would reflect [here](https://github.com/python-semantic-release/python-semantic-release/blob/8950c5236099151e13cfd1ea9dae8e8c2477221b/semantic_release/version/algorithm.py#L367).
