### ISSUE TITLE
How to upload assets in release from an (.git)ignored folder

### ISSUE THREAD

**Issue by zckv** [python-semantic-release/python-semantic-release#650]
Hello, I am currently migrating a "build and release" pipeline to semantic-release v8.X.X.

I would like to understand the way to use the tool to add built assets to a release made by the "semantic-release version" command. I can use a bash script or the Python Semantic Release GitHub Action. One possible problem is that my assets are in the **dist/** folder that is in the .gitignore file.

I am not sure that it's relevant to my problem, but I didn't understood the difference between tool.semantic_release.publish.dist_glob_patterns and tool.semantic_release.assets.

I have a python project made with poetry. The pyproject configuration is the following:
`````toml
[tool.semantic_release]
assets = []
build_command = """\
     python3 -m pip install poetry  \
     && python3 -m poetry --version \
     && python3 -m poetry build
"""
commit_message = "chore(semver): Update version to {version}"
version_toml = ["pyproject.toml:tool.poetry.version"]
 
[tool.semantic_release.publish]
dist_glob_patterns = ["dist/*"]
upload_to_vcs_release = true
`````

I would like to upload files built in ["dist/*"] directory from the build command. However, my dist folder is in the .gitignore file. 
With:
```toml
tool.semantic_release.assets = ["dist/"]
```

 the following error ensue after the build step:
```sh
Traceback (most recent call last):
  File "$HOME/.local/bin/semantic-release", line 8, in <module>
    sys.exit(main())
  File "$HOME/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "$HOME/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "$HOME/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "$HOME/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "$HOME/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "$HOME/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "$HOME/.local/lib/python3.10/site-packages/semantic_release/cli/commands/version.py", line 358, in version
    repo.git.add(all_paths_to_add)
  File "$HOME/.local/lib/python3.10/site-packages/git/cmd.py", line 741, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "$HOME/.local/lib/python3.10/site-packages/git/cmd.py", line 1315, in _call_process
    return self.execute(call, **exec_kwargs)
  File "$HOME/.local/lib/python3.10/site-packages/git/cmd.py", line 1109, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git add pyproject.toml dist/*
  stderr: 'The following paths are ignored by one of your .gitignore files:
dist
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"'
```

I added ", force=True" in semantic_release/cli/commands/version.py:358, and it print another error because it is not accepting glob paths. But I may be wrongly using the tool.

Thanks in advance for any help provided

**Comment by bernardcooke53** [comment]
Hi @zckv :wave: - you shouldn't need to add anything for `assets`, those are additional files to be committed to Git during release. `dist_glob_patterns` should be enough to ensure that your package gets uploaded to the release, and the default value is `["dist/*"]`, but you need to use `semantic-release publish` or the [`upload-to-gh-release`](https://python-semantic-release.readthedocs.io/en/latest/migrating_from_v7.html#github-action-no-longer-publishes-artefacts-to-pypi-or-github-releases) Github Action as part of your workflow.

The docs aren't specific enough on this - I will clarify them.

**Comment by zckv** [comment]
Thanks for the quick reply!
