### ISSUE TITLE
Changelog placeholder is ignored

### ISSUE THREAD

**Issue by bernardcooke53** [python-semantic-release/python-semantic-release#652]
## The problem

It looks like the placeholder  is ignored, the changelog is regenerated with all the previous commits, and not only taking the last ones, as an example https://github.com/taskforcesh/bullmq/commit/59d4d1dd67a0efbab6ff252b2a042fc61c3f4df2

## Environment

Please state which OS you are using and provide the output of the following commands:

```shell
python --version
pip --version
semantic-release --version
pip freeze
```

Python 3.10.12
pip 23.2
PSR 8.0.3

Please also indicate which Python build tool(s) you are using (e.g. `pip`, `build`,
`poetry`, etc.), including the version number too.

pipenv 2023.7.4 + setuptools 68

🛠 `Running build command: python3 setup.py sdist`

## Configuration

https://github.com/taskforcesh/bullmq/tree/master/python

## Logs

Action: https://github.com/taskforcesh/bullmq/actions/runs/5624948662/job/15242766976

**Comment by codejedi365** [comment]
Duplicate with #858 & #722

**Comment by codejedi365** [comment]
I have found a solution that works for re-introducing the placeholder version update for changelogs using jinja. It will be released as a custom template configuration first in `v9` and then converted back to the default in `v10`. Stay tuned.
