### ISSUE TITLE
automatic release to Gitlab

### ISSUE THREAD

**Issue by eitanief** [python-semantic-release/python-semantic-release#663]
_Please describe your problem. Include links to any relevant pages or files._
On latest version documentation I see no automatic release guide for Gitlab, did you stop supporting this? It was previously supported

**Comment by beatreichenbach** [comment]
You can find that information [here](https://python-semantic-release.readthedocs.io/en/latest/index.html#gitlab-gl-token).

**Comment by codejedi365** [comment]
@eitanief, GitLab is definitely still supported, and we have a issue (#666) open to write a GitLab setup page but it isn't there yet. The information we have is scattered in current issues too. If you have a specific question, please let us know
