### ISSUE TITLE
How to add changelog "version compare URLs" (in templates)?

### ISSUE THREAD

**Issue by afuetterer** [python-semantic-release/python-semantic-release#671]
Hi there, if this is already possible, please close the issue.

It would be nice to be able to generate "compare URLs" for the tagged versions and releases, to be used in the changelog template.

Example of the type of URL i mean:
https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-angular/CHANGELOG.md

Is there are way to accomplish this yet?

**Comment by bernardcooke53** [comment]
Hey @afuetterer - there's nothing defined for this in PSR, essentially these are `<project url>/compare/tagN-1..tagN` right?

You could probably accomplish this with a 2-pair window over the tags in `context.released`, maybe with something like [`cycler`](https://jinja.palletsprojects.com/en/3.1.x/templates/#jinja-globals.cycler)?

**Comment by afuetterer** [comment]
Yes, that's right (but with three dots). For example: https://github.com/python-semantic-release/python-semantic-release/compare/v8.0.4...v8.0.5

I never used Jinja templates before, so I had to do some reading first. I achieved generating those compare URLs using this in my changelog template:

```j2
{# RELEASED #}
{% set base_url = 'https://github.com/user/repo/compare/' %}
{% for version, release in context.history.released.items() %}
{% if loop.nextitem %}
{% set compare_url = base_url ~ loop.nextitem[0] + '...' ~ version %}
## [{{ version.as_tag() }}]({{ compare_url }}) ({{ release.tagged_date.strftime("%Y-%m-%d") }})
{% else %}
## {{ version.as_tag() }} ({{ release.tagged_date.strftime("%Y-%m-%d") }})
{% endif %}
```

The very first version has no previous version to be compared to, so there is no compare URL rendered.

I am not sure if it is a good idea to set the 'base_url' in the template.

Would a helper function like this make sense to you or is this overkill?

```python
def version_compare_url(self, prev_version: str, version: str) -> str:
    return f"https://{self.hvcs_domain}/{self.owner}/{self.repo_name}/compare/{prev_version}...{version}"
```

I could submit a PR if you like the idea.

**Comment by afuetterer** [comment]
Can I help with this?

**Comment by bernardcooke53** [comment]
Hey @afuetterer - absolutely, I don't see the harm in having a helper for this. Also worth noting (in case anyone reads in future) that you could also do this with a macro in the template:

```j2
{% macro version_compare_url(prev_version, version) -%}
    https://<domain>/<owner>/<repo_name>/compare/{{ prev_version }}...{{ version }}
{%- endmacro %}
```

**Comment by afuetterer** [comment]
Thank you, I will try this macro. Maybe that is already all I need. :)

**Comment by afuetterer** [comment]
Hi @bernardcooke53, the macro works like a charm, thank you.

But I just saw that there is `compare_url()` method in the `GitHub` class:

https://github.com/python-semantic-release/python-semantic-release/blob/f1452578cc064edbe64d61ae3baab4bc9bd4b666/semantic_release/hvcs/github.py#L78-L92

This cannot be used in the template, right now? commit_hash_url() and pull_request_url() are available as filters in the template. Could the compare_url() be added as well?

**Comment by codejedi365** [comment]
> [`compare_url()`] cannot be used in the template, right now? 

Yes, it's not included in the changelog context yet.

> Could the compare_url() be added as well?

It can be but we would need to implement something across all HVCS's if they have it. I have most recently added a new function and I'm starting to think that the changelog context generation needs to be refactored to just ask the hvcs for what it can support and go from there. Idk when I'll get to this but it should be simple enough and more important for the long term maintenance.

**Comment by afuetterer** [comment]
Thanks for the update.

**Comment by afuetterer** [comment]
Thank you, I will try the new filters this weekend. This is awesome.

**Comment by codejedi365** [comment]
@afuetterer, I didn't yet release it but it did get merged to the master branch and will be a part of this weekends release. I'm trying to include a bit more than one feature each release as updating dependencies weekly is annoying. 

But as you have the enthusiasm to try this out immediately, if you can pip install from the repostory you can try this stuff out. The docs are also updated in the repo and you can build & serve them locally with sphinx

**Comment by afuetterer** [comment]
Did not realize that, I can of course wait for the next release.

**Comment by afuetterer** [comment]
Hi @codejedi365, I finally tested the new filters and got an exception already.

How to deal with `jinja2.exceptions.UndefinedError: 'compare_url' is undefined`?

I have 9.6.0 locally and the same version as GHA. I get the same error locally and using the GHA.

I did not specify hvcs or remote type as GitHub, because that is the default. Do I need to somehow enable or import the filters?

**Comment by codejedi365** [comment]
Hello @afuetterer, thanks for the update and notice of the rather unfortunate outcome. No, you do not need to specify GitHub type as it is the default and the filters are added to the context by default. 

Recommend taking a look at my [unit test fixture](https://github.com/python-semantic-release/python-semantic-release/blob/master/tests/unit/semantic_release/changelog/test_changelog_context.py#L23) which is where I wrote a jinja template with all the GitHub specific filters. It seems to render fine although it renders a string versus from a file during the test.

My initial estimate is possibly a syntax error in your template for how you are calling the filter.

**Comment by afuetterer** [comment]
> My initial estimate is possibly a syntax error in your template for how you are calling the filter. Filters must have their first parameter piped (`|`) to them and then second parameter in parentheses.

Thank you, that was my mistake. Previously I had custom macro, which I could call like a Python function in the template. Now I call the filter properly the exception is gone.
