### ISSUE TITLE
Add doc for configuration VERSION file

### ISSUE THREAD

**Issue by mxdev88** [python-semantic-release/python-semantic-release#689]
https://python-semantic-release.readthedocs.io/en/latest/configuration.html#version-variables-list-str

I have a VERSION text file in my repo that contains the version number. How do I have the version updated on release?

Happy to contribute a PR if someone is able to explain the configuration.

**Comment by bernardcooke53** [comment]
Hey @mxdev88 :wave: 

There isn't a configuration option for this, but it's really simple to do with output redirection. For example, if you're working in bash:

```bash
NEXT_VERSION="$(semantic-release version --print)"
echo "$NEXT_VERSION" > VERSION
```

If you want it printed in the output too:

```bash
semantic-release version --print | tee VERSION
```

is a handy one-liner.
