### ISSUE TITLE
Push failed when using self-managed GitLab instance.

### ISSUE THREAD

**Issue by miaoz2001** [python-semantic-release/python-semantic-release#690]
Hi, 
I am new to the python semantic release, just tried a bit but I like it.
It works all good with only one issue,
We have a self-managed GitLab instance, so when I push it pushed to the wrong url. As in the log it says

```
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git push https://*****:*****@gitlab.com/xxx/django-xxx.git master
  stderr: 'remote: HTTP Basic: Access denied. The provided password or token is incorrect or your account has 2FA enabled and you must use a personal access token instead of a password. See https://gitlab.com/help/topics/git/troubleshooting_git#error-on-git-fetch-http-basic-access-denied
fatal: Authentication failed for 'https://gitlab.com/xxx/django-xxx.git/''
```

the gitlab we have is something like https://gitlab.example.com/.

Is there a way to config the remote url? Thanks!

**Comment by domste** [comment]
I have not tried it yet, but looks like you have to set it in pyproject.toml:

```
[tool.semantic_release.remote]
type = "gitlab"
token = { env = "GL_TOKEN" }
domain = "my-gitlab.mydomain.com"
api_domain = "/api/v4"
```


Checkout: 
https://github.com/python-semantic-release/python-semantic-release/blob/3abfb7ac216b9ad439de24fda60eca84038e850e/semantic_release/cli/config.py#L348


Seems like there still is a lot of documentation missing in this regard.

**Comment by miaoz2001** [comment]
Hi @domste ,

Thanks for the hint, it works after setting it in the config file! You saved my day!

**Comment by Sieboldianus** [comment]
Wow, another thing to add to [#666](https://github.com/python-semantic-release/python-semantic-release/issues/666)
