### ISSUE TITLE
re.match for select_branch_options rather than re.fullmatch

### ISSUE THREAD

**Issue by zckv** [python-semantic-release/python-semantic-release#709]
Hello 👋

Is the use of re.match rather than re.fullmatch a bug or a feature ?

[Here](https://github.com/python-semantic-release/python-semantic-release/blob/3abfb7ac216b9ad439de24fda60eca84038e850e/semantic_release/cli/config.py#L227C1-L227C1)

Using [re.match](https://docs.python.org/3/library/re.html#re.match) will return something True if a substring of the branch name match the python regex. 

So for example, '([0-9]*)' will match "1-correct-issue" as well as "my-br4nch". Using fullmatch should force the branch name to match the python regex pattern, as documented in the Multibranch Releases documentation.

**Comment by bernardcooke53** [comment]
Hey @zckv - it's a feature, because if you want an exact match you can use the `^$` anchors for the start/end of the string. But the docs don't call this out explicitly so agreed it might be helpful to state that the match is done with `re.match`
