### ISSUE TITLE
What will be the effect of reverting code on the release workflow? 

### ISSUE THREAD

**Issue by rizahmeds** [python-semantic-release/python-semantic-release#718]
Let's say if I want to go 7 commits behind the master and do a force push i.e:
`git reset --hard HEAD~7`
`git push -f (force push to master)`

what will happen to release workflow?
CHANGELOG.md file will get updated accordingly?

**Comment by zckv** [comment]
Hello 👋 

I am a nobody on this project, but I did have to revert some commit on a master branch, on a project that use semantic-release.

On `reset --hard`, tags are not moved, they still reference the same commit. On new commit and versions, `semantic-release version` will detect the old tags and will display `No release will be made, VERSION has already been released!` until the project version exceed the one before it was reset.

To cleanly reset, you should also remove the corresponding tags and GitHub release. Then semantic-release works fine.
