### ISSUE TITLE
Template for v7 style changelogs

### ISSUE THREAD

**Issue by nejch** [python-semantic-release/python-semantic-release#737]
Not sure if I've missed this discussion somewhere already, feel free to link if so!

I prefer the old format as it's closer to the node semantic-release package and doesn't include entire commit messages / chore types that usually don't belong in the changelog (polluting it with dependency update for example).

Has anyone already come up with a template to match the old style already or would it make sense to include one in the package itself?

**Comment by codejedi365** [comment]
@nejch, I actually have come up with a template that is much more similar to the JS one with some enhancements. I intend to release it as part of PSR soon. 

I agree the v8 one is a bit bloated with full commit bodies. As for a specific v7 template, it would take me a bit to revive it.

**Comment by nejch** [comment]
@codejedi365 that's great, yeah actually going close to the node implementation would be the way to go IMO. At the time it made more sense to me to just revert, but this sounds good! Thanks.

**Comment by codejedi365** [comment]
Still in progress but it hasn't moved recently as I've been unavailable over the last month for making significant progress.

**Comment by codejedi365** [comment]
Getting close to resolution of this issue. This ultimately rests upon the need to handle squash commits effectively before I can change the default template. I am going to publish a large change this weekend that illustrates prepending new release notes into an existing changelog (a feature lost in v8). 

I will try to post some example templates in the new style here. The next two months should allow me to make these changes and publish a new default.

**Comment by codejedi365** [comment]
Besides the work I've been doing to improve the default changelog. I believe this has already been answered in #982 with provided examples from the community.
