### ISSUE TITLE
feat: support GitHub M1 runners

### ISSUE THREAD

**Issue by cemlyn007** [python-semantic-release/python-semantic-release#738]
## Description
Support the GitHub action working on the GitHub M1 runners <3

*A clear and concise description of your idea.*
<img width="910" alt="image" src="https://github.com/python-semantic-release/python-semantic-release/assets/49565105/4c05d723-df73-4ef3-9671-3672e4d2cc85">

## Use cases
M1 Runners

*List some reasons this would be useful.*
* Semantic-release action can be used on M1 runners

**Comment by bernardcooke53** [comment]
Hey @cemlyn007 - try using `v8.3.0`, @zckv has just converted the action to composite so :crossed_fingers: this isn't an issue any more!

**Comment by cemlyn007** [comment]
Sweet, thanks mate!
