### ISSUE TITLE
(Another) Question about customizing the changelog template

### ISSUE THREAD

**Issue by afuetterer** [python-semantic-release/python-semantic-release#742]
Hi @bernardcooke53,

I have another question about customizing the changelog template.

Is it possible to change the names/labels of commit types?

I really like the default changelog of python-semantic-release. I just wonder, if can I somehow rename the types, e.g. "Feature" -> "Features", "Fix" -> "Bug Fixes". I can hard-code a mapping in the template. Is there a better approach, can this be customized in the pyproject.toml without writing a custom commit parser?

Another question would be: Can I re-order the commit types? They are sorted alphabetically (using Jinja's `dictsort`). Is there a way to set up a default ordering?

Thanks.

**Comment by bernardcooke53** [comment]
Hey @afuetterer - sure thing, I'd suggest for remapping doing something like:

```jinja

{% set commit_type_remaps = {"Feature": "Features", ...} %}

...
### {{ commit_type_remaps.get(type_, type_ | capitalize) }}

```

Regarding ordering - do you have something specific in mind? You could always replace the for-loop with one that
goes 

```jinja
{% for type_ in [<list of types in the order you'd like>] %}
{% set commits = release["elements"][type_] %}
```

**Comment by afuetterer** [comment]
Excellent, thank you. I will try those suggestions.

Regarding ordering: I would like to order the changes, e.g., like this (not alphabetically):
- "Features"
- "Bug Fixes"
- ...

**Comment by afuetterer** [comment]
@bernardcooke53: I stumbled upon this setup, which I really like:

https://github.com/KSmanis/pip-autocompile/blob/master/templates/CHANGELOG.md.j2

It does the rename and reorder in a single step.

I did it like this in the end. What do you think about the approach?
