### ISSUE TITLE
Changelog only generated in subfolder.

### ISSUE THREAD

**Issue by gordianbahri** [python-semantic-release/python-semantic-release#744]
## The problem

My git repository consist of the main folder that should contain general package data like the changelog, license etc. and then I have the subfolder _myproject_ containing all the source code.

When I `semantic-release version` within _myproject_ (so the subfolder) I get a correct changelog with all my commits.  However, my __version__ that is within setup.py of the parent folder won't be updated.

If I'm within the main folder (so one level above _myproject_ where my setup.py, .gitignore, pyproject.toml, and all these configuration related files are stored, it's the exact other way around.
In this cas my __version__ is updated properly, but I get a changelog file that only contains all the versions but without any contents.

## Expected behavior

The expected behavior would be that I `semantic-release version` in the main folder and that this would create a proper version bump like it already does when in the parent folder. However, additionally it should also create a full working changelog like when in _myproject_.

## Environment

I'm working on WSL2 Debain using conda.

```
Python 3.11.4
pip 23.2.1 from /home/myuser/anaconda3/envs/myenv/lib/python3.11/site-packages/pip (python 3.11)
semantic-release, version 8.1.1
```

## Configuration

```
[tool.semantic_release]
assets = []
version_variables = ["setup.py:__version__"]
commit_message = "{version}"
commit_parser = "angular"
logging_use_named_masks = false
major_on_zero = true
tag_format = "v{version}"

[tool.semantic_release.branches.main]
match = "(main|master)"
prerelease_token = "rc"
prerelease = false

[tool.semantic_release.changelog]
template_dir = "templates"
changelog_file = "CHANGELOG.md"
exclude_commit_patterns = []

[tool.semantic_release.changelog.environment]
block_start_string = "{%"
block_end_string = "%}"
variable_start_string = "{{"
variable_end_string = "}}"
comment_start_string = "{#"
comment_end_string = "#}"
trim_blocks = false
lstrip_blocks = false
newline_sequence = "\n"
keep_trailing_newline = false
extensions = []
autoescape = true

[tool.semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
default = "Semantic Bot <Semantic Bot>"

[tool.semantic_release.commit_parser_options]
allowed_tags = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "style", "refactor", "test"]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]

[tool.semantic_release.remote]
name = "origin"
type = "github"
ignore_token_for_push = false

[tool.semantic_release.remote.token]
env = "GH_TOKEN"

[tool.semantic_release.publish]
dist_glob_patterns = ["dist/*"]
upload_to_vcs_release = true
```
^^pyproject.toml
The GH_TOKEN is set as env var.

## Additional context

This was done running the command stated above, not using GitHub actions. There are no additional build tools included.

**Comment by bernardcooke53** [comment]
Hey @gordianbahri - if can you paste the output of 

```bash
tree -L 2
```

it would help to see the project structure. Can you also try to run `semantic-release -c myproject/pyproject.toml version` from the root of the repository?
