### ISSUE TITLE
upgrade gitlab plugin

### ISSUE THREAD

**Issue by damnms** [python-semantic-release/python-semantic-release#759]
## Description

there is a newer version of the gitlab plugin available, but semantic release requires 3.8 (4.1.1 is available now)

## Use cases

https://python-gitlab.readthedocs.io/en/stable/changelog.html#v4-0-0-2023-10-17 - there are quiet some reasons to upgrade

**Comment by bernardcooke53** [comment]
This should be fixed by #748
