### ISSUE TITLE
Dropping support for Python 3.7

### ISSUE THREAD

**Issue by bernardcooke53** [python-semantic-release/python-semantic-release#763]
## Description

Python 3.7 is very safely EOL now, having been out of security support for 5+ months. While there's been no great need to break compatibility, upstream dependencies are dropping support and becoming harder to keep in-line. By having to constrain our dependencies to versions which still support 3.7, we're making it difficult to install PSR in an environment alongside other packages when do not support 3.7 and have pinned to versions higher than we can accommodate, and this problem obviously only worsens with time.

The [download stats](https://pypistats.org/packages/python-semantic-release) for the last 120 days also indicate that the majority of users are running more modern Python versions:

![image](https://github.com/python-semantic-release/python-semantic-release/assets/66492393/81e171cc-9195-486c-991a-9c6fad82d5f4)

As a result of this, the intention is to release a breaking change on **February 3rd, 2024**, after which new versions of Python Semantic Release will no longer support Python 3.7.

**Comment by zckv** [comment]
Hello 👋 

Will there be other breaking change for PSR 9.0 ?

**Comment by codejedi365** [comment]
We should make a separate ticket that summarizes the plan for the next major release, and it would reference this ticket and/or others.

I have two in mind but I'm not sure I'll have them done by 24 Feb and that's of course if we are willing to change the defaults to what I would like them to be. Was planning to add them as a not default feature first, that would then become the default with the next major release.
