### ISSUE TITLE
Docs: read-the-docs failure to update

### ISSUE THREAD

**Issue by codejedi365** [python-semantic-release/python-semantic-release#770]
@bernardcooke53 , @relekang, After the new release of `v8.4.0` and `v8.5.0` last week the documentation at https://python-semantic-release.readthedocs.io/en/latest/ is still stuck on `v8.3.0`.  I'm not sure if this is a mistake, or internal failure but hopefully one of you can take a look?

**Comment by relekang** [comment]
Built it manually now, it looks like the webhook is failing with:
```
{
  "detail": "Payload not valid, invalid or missing signature"
}
```
Will try to look into this soon. @bernardcooke53 Do you have the same username at readthedocs so i can add you?

**Comment by relekang** [comment]
This is fixed now

**Comment by bernardcooke53** [comment]
Hey @relekang - yep, it's `bernardcooke53` 🙏

**Comment by relekang** [comment]
Sent you an invite now
