### ISSUE TITLE
Add support for Bitbucket

### ISSUE THREAD

**Issue by beatreichenbach** [python-semantic-release/python-semantic-release#784]
## Description

Add support for the Bitbucket remote vcs.

## Use cases

Bitbucket doesn't support releases like Github but I added a skeleton class anyway so that users can use `semantic-release version` without having to use the `--no-vcs-release flag`. It still pushes a tag to the remote vcs which creates archives so it's nice to be able to use semantic-release without necessarily having actual releases in the remote vcs.

## Possible implementation

https://github.com/python-semantic-release/python-semantic-release/pull/783

**Comment by codejedi365** [comment]
Released in `v9.1.0`
