### ISSUE TITLE
Releasing a python >=3.11 package

### ISSUE THREAD

**Issue by bdraco** [python-semantic-release/python-semantic-release#801]
It looks like [python 3.10](https://github.com/python-semantic-release/python-semantic-release/blob/1d2bbdf23aab816cd9d6e26f537b5cec9e39dede/Dockerfile#L2C3-L2C3) is used to do the releasing, but I have a package that is python 3.11+ only https://github.com/home-assistant-libs/home-assistant-bluetooth/issues/30

This means the release workflow fail since `The currently activated Python version 3.10.13 is not supported by the project (>=3.11,<3.13).
Trying to find and use a compatible version.` 

sample run: https://github.com/home-assistant-libs/home-assistant-bluetooth/actions/runs/7482007644/job/20364775062 

Is there an approved/good way to use a newer python in the build process?

**Comment by codejedi365** [comment]
After reviewing your logs, this does not look like a semantic-release problem. 

When semantic-release runs your build command, you have a number of errors that happen. First, pip throws errors about being unable to write to the cache, then it fails to resolve some dependency conflicts. Poetry is the one throwing the error about the python version I believe.

Just checked your CI configuration and you didn't set up your python environment in your release job. It can't find the right python version because of this, I believe.

**Comment by bdraco** [comment]
> Just checked your CI configuration and you didn't set up your python environment in your release job. It can't find the right python version because of this, I believe.

It looks like its definitely running setup python before the failing step.

I guess its using the wrong python somehow
<img width="570" alt="Screenshot 2024-01-11 at 9 40 41 AM" src="https://github.com/python-semantic-release/python-semantic-release/assets/663432/c6493dda-c94d-4fdf-876a-ab3a97b9b9ec">

**Comment by bdraco** [comment]
I think the setup python is running outside the container, and its 3.10.x in the container

**Comment by bdraco** [comment]
I got it to work by forking it and adjusting the python version in the docker file

https://github.com/Bluetooth-Devices/python-semantic-release/commit/e7976f02e446cb797c91514b3660b91644bd3a3f

**Comment by codejedi365** [comment]
@bdraco, my mistake, I think I was looking at the wrong job / pipeline earlier.  Yes, good job finding a solution. I didn't write the GitHub Action and I didn't realize it was its own container which does hardcode the python version.  

I'm not sure what the best course of action is here for compatibility (other than not use docker to distribute the action)... will have to think on it.

**Comment by bdraco** [comment]
Thanks for looking.

cheers

**Comment by bdraco** [comment]
Thanks!
