### ISSUE TITLE
Why is in every example git config for user.email and user.name set?

### ISSUE THREAD

**Issue by rosaLux161** [python-semantic-release/python-semantic-release#812]
In almost every example is before running sematic-release the git config for user.email and user.name set.

E.g.:

```
    # - git config user.name xxx
    # - git config user.email xxx
    - git checkout $CI_COMMIT_BRANCH
    - semantic-release version
```

Removing these setting does't change the behaviour of pushing changelogs. Also these settings are ignored and set by the semantic-release defaults: `semantic-release <semantic-release>`: https://python-semantic-release.readthedocs.io/en/latest/configuration.html#commit-message-str

Why is it given in every example setup?

**Comment by codejedi365** [comment]
> Why is it given in every example setup?

Traditionally, CI's do not have git configured automatically which will cause failures for `git` when trying to make a local commit or create a local tag. I'm sure this is why we had it in there.

> Removing these setting does't change the behaviour of pushing changelogs. Also these settings are ignored and set by the semantic-release defaults: `semantic-release <semantic-release>`: https://python-semantic-release.readthedocs.io/en/latest/configuration.html#commit-message-str

However, I don't know when we added the configuration option to set the commit author and commit message string but I did verify that all the version commands do pass an author and email to the git command when semantic-release executes a history altering modification.  If the user does not provide a `commit_author` the default is used, so currently the code will never execute without a value set.  I also verified that Git `user.name` and `user.email` are not required for checkout and pushes.

I believe you are correct that the git configurations can be removed from the docs at this point. Thank you for making us aware of these extra steps.
