### ISSUE TITLE
GitHub Actions can't create release: `ValueError: release id for tag <tag> not found, and could not be created`

### ISSUE THREAD

**Issue by charlesthomas** [python-semantic-release/python-semantic-release#818]
## The problem

Trying to use GitHub Action, it's throwing an error that isn't being logged.

[see the logs here](https://github.com/charlesthomas/templatron/actions/runs/7680236115/job/20932031435)

## Expected behavior

GitHub Release is created without error **OR** the error is logged if it occurs.

## Environment

I'm using the GitHub Actions example workflow [from the docs](https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/github-actions.html) (except I changed the branch to `main`)

## Configuration

[pyproject.toml](https://github.com/charlesthomas/templatron/blob/main/pyproject.toml)

**Comment by codejedi365** [comment]
I don't think your token is being passed to the Action. See the 2 warnings in the logs about the empty or missing token. 

The token is required to write to the GitHub API which is how we create and write the release notes to the Releases section.

**Comment by codejedi365** [comment]
@charlesthomas, any update?

**Comment by charlesthomas** [comment]
> @charlesthomas, any update?

sorry, this is a personal side project. took me a while to get back to it.

... this was misconfiguration on my part.

although i completely missed the log line you pointed out. maybe that should be an error not a warning?

**Comment by codejedi365** [comment]
> sorry, this is a personal side project. took me a while to get back to it.

No problem, glad it is resolved. 

> although i completely missed the log line you pointed out. maybe that should be an error not a warning?

Well likely not going to turn those specific warnings into errors for where they occur in the code but likely before you hit a line of code that needs a token it should be a captured error on our part. We have numerous control flows that never actually need the token that we don't want to break by creating an error so early in the execution.
