### ISSUE TITLE
Github release creation fails with "Error: Unauthorized" despite GH_TOKEN

### ISSUE THREAD

**Issue by Sieboldianus** [python-semantic-release/python-semantic-release#825]
## The problem

I am trying to publish a release, as always, manually, through `semantic-release -vv publish` (after `semantic-release -v version`).

However, it is failing with:
```
semantic-release -vv publish
[...]
DEBUG    [semantic_release.helpers] DEBUG helpers.parse_git_url: Parsing git url 'git@github.com:Sieboldianus/TagMaps.git'                                                                                            helpers.py:112
DEBUG    [urllib3.connectionpool] DEBUG connectionpool._new_conn: Starting new HTTPS connection (1): api.github.com:443                                                                                       connectionpool.py:1052
DEBUG    [urllib3.connectionpool] DEBUG connectionpool._make_request: https://api.github.com:443 "GET /repos/Sieboldianus/TagMaps/releases/tags/v0.22.8 HTTP/1.1" 401 80
DEBUG    [semantic_release.hvcs.github] DEBUG helpers._wrapper: Github.get_release_id_by_tag -> None                                                                                                                   helpers.py:56
WARNING  [semantic_release.hvcs.github] WARNING github.upload_dists: No release corresponds to tag v0.22.8, can't upload dists                                                                                         github.py:252
DEBUG    [semantic_release.hvcs.github] DEBUG helpers._wrapper: Github.upload_dists -> 0                                                                                                                               helpers.py:56
```

What is strange is that `401` means "unauthenticated". But I can access the tag url just fine in the browser: https://api.github.com/repos/Sieboldianus/TagMaps/releases/tags/v0.22.8

The same applies to the version command, which also fails to create the release for some unknown reason:
```
INFO     [semantic_release.hvcs.github] INFO github.create_or_update_release: Creating release for v0.22.10
DEBUG    [semantic_release.hvcs.github] DEBUG helpers._wrapper: create_release(<semantic_release.hvcs.github.Github object at 0x7
                    '# v0.22.10 (2024-02-06)', False, )
INFO     [semantic_release.hvcs.github] INFO github.create_release: Creating release for tag v0.22.10
DEBUG    [urllib3.connectionpool] DEBUG connectionpool._new_conn: Starting new HTTPS connection (1): api.github.com:443
DEBUG    [urllib3.connectionpool] DEBUG connectionpool._make_request: https://api.github.com:443 "POST /repos/Sieboldianus/TagMap
                    HTTP/1.1" 404 None
DEBUG    [semantic_release.hvcs.github] DEBUG github.create_or_update_release: error creating release: 404 Client Error: Not Foun
                    https://api.github.com/repos/Sieboldianus/TagMaps/releases
DEBUG    [semantic_release.hvcs.github] DEBUG github.create_or_update_release: looking for an existing release to update
DEBUG    [semantic_release.hvcs.github] DEBUG helpers._wrapper: get_release_id_by_tag(<semantic_release.hvcs.github.Github object
                    'v0.22.10', )
```

I checked the `GH_TOKEN` twice and it is correct. Below output I get when setting GH_TOKEN and running `version`:

```
INFO     [semantic_release.hvcs.github] INFO github.remote_url: requested to use token for push but no token set,   github.py:270
                    ignoring...
[...]
 INFO     [semantic_release.hvcs.github] INFO github.create_or_update_release: Creating release for v0.22.11         github.py:167
DEBUG    [semantic_release.hvcs.github] DEBUG helpers._wrapper: create_release(<semantic_release.hvcs.github.Github helpers.py:45
                    object at 0x7f397f4702d0>, 'v0.22.11', '# v0.22.11 (2024-02-06)', False, )
INFO     [semantic_release.hvcs.github] INFO github.create_release: Creating release for tag v0.22.11               github.py:107
DEBUG    [urllib3.connectionpool] DEBUG connectionpool._new_conn: Starting new HTTPS connection (1):       connectionpool.py:1052
                    api.github.com:443
DEBUG    [urllib3.connectionpool] DEBUG connectionpool._make_request: https://api.github.com:443 "POST      connectionpool.py:546
                    /repos/Sieboldianus/TagMaps/releases HTTP/1.1" 401 80
DEBUG    [semantic_release.hvcs.github] DEBUG github.create_or_update_release: error creating release: 401 Client   github.py:171
                    Error: Unauthorized for url: https://api.github.com/repos/Sieboldianus/TagMaps/releases
DEBUG    [semantic_release.hvcs.github] DEBUG github.create_or_update_release: looking for an existing release to   github.py:172
                    update
```

> Error: Unauthorized 

Why am I not authenticated?

This looks also strange:

> requested to use token for push but no token set, ignoring... github.py:270

If I `echo $GH_TOKEN`, I can see that it is set and correct.

I have also tested using `ignore_token_for_push = true`, so it can use my ssh agent, but this also leads to the same error.

## Expected behavior

Release gets uploaded to VCS.

## Environment

Please state which OS you are using and provide the output of the following commands:

```shell
python --version
> Python 3.11.5
pip --version
> pip 23.3.1
semantic-release --version
> semantic-release, version 8.7.0
pip freeze
> annotated-types==0.6.0
build==1.0.3
certifi==2023.11.17
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
cryptography==41.0.7
docutils==0.20.1
dotty-dict==1.3.1
gitdb==4.0.11
GitPython==3.1.40
idna==3.6
importlib-metadata==7.0.0
importlib-resources==6.1.1
jaraco.classes==3.3.0
jeepney==0.8.0
Jinja2==3.1.2
keyring==24.3.0
markdown-it-py==3.0.0
MarkupSafe==2.1.3
mdurl==0.1.2
more-itertools==10.1.0
nh3==0.2.14
packaging==23.2
pkginfo==1.9.6
pycparser==2.21
pydantic==2.5.2
pydantic_core==2.14.5
Pygments==2.17.2
pyproject_hooks==1.0.0
python-gitlab==3.15.0
python-semantic-release==8.7.0
readme-renderer==42.0
requests==2.31.0
requests-toolbelt==1.0.0
rfc3986==2.0.0
rich==13.7.0
SecretStorage==3.3.3
shellingham==1.5.4
smmap==5.0.1
tomlkit==0.12.3
twine==4.0.2
typing_extensions==4.8.0
urllib3==2.1.0
zipp==3.17.0
```

## Configuration

[pyproject.toml](https://github.com/Sieboldianus/TagMaps/blob/master/pyproject.toml)
[make_release.sh](https://github.com/Sieboldianus/TagMaps/blob/master/make_release.sh)

**Comment by Sieboldianus** [comment]
Yes, the `GH_TOKEN` is exported. What I am doing is modifying the conda activate script to export the necessary values, and then unset on deactivation:
```bash
nano ~/miniconda3/envs/semantic-release/etc/conda/activate.d/env_vars.sh
nano ~/miniconda3/envs/semantic-release/etc/conda/deactivate.d/env_vars.sh
```

`activate.d/env_vars.sh`:
```bash
#!/bin/sh

export GH_TOKEN='...'
export GL_TOKEN='...'
export PYPI_USERNAME='Sieboldianus'
export PYPI_PASSWORD='...'
```

`deactivate.d/env_vars.sh`:
```bash
#!/bin/sh

unset GL_TOKEN
unset GH_TOKEN
unset PYPI_USERNAME
unset PYPI_PASSWORD
```

This has worked since eons. My workflow:
```bash
conda activate semantic-release
echo $GH_TOKEN
> # prints GH_TOKEN
semantic-release version
```


Do you have any idea how I can go further to debug this? I looked at the code in `github.py`, but I don't know where the token comes from or is handed over. I could maybe add a check to see where the token got lost (because apparently, triggering the "no token"-warning means that it is not present in semantic-release anymore. The question is, was it ever read or not noticed at all?

**Comment by Sieboldianus** [comment]
@codejedi365 

Well, the devil is in the details. And your input highlighted the detail:
For some reason, I had both `GL_TOKEN` and `GH_TOKEN`. (I think _maybe_ I needed GL_TOKEN somewhere else and uncommented it, but forgot to comment it out again in `activate.d/env_vars.sh`.

`unset GL_TOKEN` before `semantic-release version` solved the problem.

Now, this was obviously my mistake. For convenience, however, it would be great if semantic-release could warn if both tokens are set (and not simply fail with an empty GH_TOKEN; because the GH_TOKEN indeed _is_ set). The behavior here is just a little bit unexpected.

Thank you for your help! Apologies for this issue and not seeing my obvious mistake.

**Comment by codejedi365** [comment]
> The question is, was it ever read or not noticed at all?

I'm starting to think it was picked up because I didn't see the warning at the top from when it reads the config. The other token error is also odd but that comes from right before it is used in the GitHub file.  I know this is obvious but have you checked the expiration date of the token and verified it has the correct api permissions. GitHub has been making the transition to more granular token permission model and that could be happening. But we do need to make sure it is sent.

> Do you have any idea how I can go further to debug this? 

If you use VSCode, in your TagMaps project, create a Python `launch.json` configuration, and set the program to the full path to the `$VIRTUAL_ENV/bin/semantic_release` and set the args array accordingly. Set your ENV variables as well. In the editor open the `$VIRTUAL_ENV/lib/**/semantic_release/cli/config.py`, and place a breakpoint in the `EnvConfigVar.getvalue()` and also the `RuntimeContext.from_raw_config()`. This is where it loads the configuration and creates the GitHub object.

Furthermore, put a breakpoint in the `$VIRTUAL_ENV/lib/**/semantic_release/cli/commands/version.py:version()`, so then you can walk the execution code.

If you don't use VSCode, make a temporary edit to the files where I said to put breakpoints and use pythons debugger at those spots via:

```py
import pdb; pdb.set_trace()
```

**Comment by Sieboldianus** [comment]
I will try asap (likely tomorrow). Will edit this post with results. Thank you very much!

**Comment by codejedi365** [comment]
No worries! It happens to all of us, literally! I'm glad you got it resolved and learned some things in the process!
