### ISSUE TITLE
Help not shown if semantic-release not configured

### ISSUE THREAD

**Issue by aeisenbarth** [python-semantic-release/python-semantic-release#840]
## The problem

Apparently after upgrading from 7.x, the configuration needs changes which I am trying to try out and debug. For this, I want to see the available CLI commands and parameters. I am on a non-default branch (not `main`).

However, help is not shown as long as I don't have defined release groups:
```bash
$ semantic-release version -h
branch 'feature/redesign' isn't in any release groups; no release will be made
```

## Expected behavior

`--help` never fails.

## Environment

Please state which OS you are using and provide the output of the following commands:

```shell
$ python --version
Python 3.9.17
$ pip --version
pip 23.0.1
$ semantic-release --version
semantic-release, version 9.1.0
$ pip freeze
annotated-types==0.4.0
certifi==2023.7.22
charset-normalizer==3.2.0
click==8.1.6
dotty-dict==1.3.1
gitdb==4.0.10
GitPython==3.1.31
idna==3.4
importlib-resources==6.1.1
Jinja2==3.1.2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
mdurl==0.1.2
pydantic-core==2.16.2
pydantic==2.6.1
Pygments==2.16.1
python-gitlab==3.14.0
python-semantic-release==9.1.0
requests==2.31.0
rich==13.5.2
shellingham==1.5.0.post1
smmap==5.0.0
tomlkit==0.12.1
typing-extensions==4.9.0
urllib3==1.26.18
zipp==3.16.2
```

Please also indicate which Python build tool(s) you are using (e.g. `pip`, `build`,
`poetry`, etc.), including the version number too.

## Configuration

Please add your `semantic-release` configuration, and if applicable also provide
your `build-system` configuration from `pyproject.toml`.
```
[tool.semantic_release]
version_source="commit"
tag_format="my-module-v{version}"
repository="gitlab"
version_variable = "my_module/__init__.py:__version__"
```

**Comment by codejedi365** [comment]
@aeisenbarth, thanks for the bug report. Definitely not the intended behavior, will fix.

**Comment by codejedi365** [comment]
@aeisenbarth, if you upgrade to `v9.2.2`, you should no longer experience this issue, please let me know if your problem persists. Cheers.
