### ISSUE TITLE
Append release notes to changelog instead of overwrite

### ISSUE THREAD

**Issue by Rebekah-Chuang** [python-semantic-release/python-semantic-release#858]
Hello!

I'm wondering if there's a way to simply append the latest release notes to the changelog instead of overwriting the entire changelog. I'm asking because, at the beginning of the project, I didn't follow the correct commit message format, resulting in most of them being unrecognized. My solution was to manually update the changelog for those incorrect commit messages. I thought it would update the changelog based on the previous version, but it instead overwrites the entire changelog, causing the unknown section to reappear. If this is not currently possible, I believe it could be a beneficial feature, as it would make the changelog neater (I've noticed that the changelog for this repo also includes an unknown section in earlier versions).

Thank you in advance!

**Comment by codejedi365** [comment]
@Rebekah-Chuang, unfortunately there is not a current method for only prepending the latest release information. I do believe there was a previous ticket that mentioned this but it seems nothing specifically came of it. I  agree it would be a useful feature to provide methods of adoption of this project to an existing project.

**Comment by Rebekah-Chuang** [comment]
Hi @codejedi365, sorry for the late response, thank you so much for replying, I think the ticket you mentioned was #722. Hope to see this feature in the future!

**Comment by codejedi365** [comment]
@Rebekah-Chuang, given the complexities discussed in #722, I'm not sure if or when this feature would actually be solved, but there's may be an alternative.

You could use the changelog template directory, to write a custom template which does not loop through all of the versions as the provided default does.  Jinja2 also provides the ability to import other files and macros. Potentially, you could correct your changelog for the previous versions and store that as a file such as `3.x_CHANGELOG.md`. Then in your custom changelog template abort the loop when the version matches `3.x` and just import the other file and append it. This is a bit exploratory as I have not done this myself but thinking about it now I believe it accomplishes what you need.

**Comment by codejedi365** [comment]
Still in the backlog however as I'm reviewing the changelog architecture and the performance of PSR, I am finding this issue to be one of more importance and I might of devised a way to make this a reality. Hopefully over the next few months I can implement a solution.

**Comment by codejedi365** [comment]
I have found a solution that works for re-introducing the placeholder version update for changelogs using jinja. It will be released as a default changelog variation (toggled by a config option, `changelog.mode`) soon in `v9`. If you have a custom template configuration, you will need to modify your templates for the newly provided context variables for use.

My plan is to converted the placeholder functionality back to the default in `v10`. Stay tuned.

**Comment by codejedi365** [comment]
### :tada: This resolution has been included in version 9.10.0 :tada:

The release is available on:
- [PyPi package](https://pypi.org/project/python-semantic-release/9.10.0/)
- [GitHub release](https://github.com/python-semantic-release/python-semantic-release/releases/tag/v9.10.0)

----

Check out the Changelog Templates in the documentation to learn about the "update" mode.
