### ISSUE TITLE
Unclear how to release a patch of an old version

### ISSUE THREAD

**Issue by silverjam** [python-semantic-release/python-semantic-release#861]
I wasn't able to find a forum for general questions, so if there's a better place to ask general support questions... please let me know.

That said, I am trying to understand how we would configure `python-semantic-release` to enable us to release a patch version or hotfix of an old version.  In our code base we have versions like `0.2.11` and `0.15.12` -- if we currently have `0.2.11` pushed to a production environment and need to release a patch (or hotfix) version (for example `0.2.12` or `0.2.12-hotfix.1` if attempting a "prerelease") when using `python-semantic-version` it seems to want the next release to be `0.15.13`.

In this scenario we've created a branch from an old version of our `main` branch where the last tagged version is `0.2.11` -- so the "next" release we'd expect is `0.2.12` or `0.2.12-hotfix.1`.

Is there a pattern or path where we could implement our expected behavior? Thanks!

**Comment by codejedi365** [comment]
This is definitely supposed to be a supported ability via release branches but I do believe there likely is a bug with tag resolution that I haven't been able to solve yet.

**Comment by codejedi365** [comment]
> I wasn't able to find a forum for general questions, so if there's a better place to ask general support questions

This is the correct location for general support questions as of now.

> In this scenario we've created a branch from an old version of our `main` branch where the last tagged version is `0.2.11` -- so the "next" release we'd expect is `0.2.12` or `0.2.12-hotfix.1`.
> 
> Is there a pattern or path where we could implement our expected behavior? Thanks!

I have simulated your scenario as much as I understood and PSR will provide `0.2.12` if the configuration has `prerelease = False`.  If prerelease is set to `true`, it does jump to `0.15.12` as the base version to increment from.  I think latter section is a bug but I will have to apply further testing.

The configuration concept I used is documented under the Mulitbranch releases section of the documentation.  In your case, you are creating a second non-prerelease channel for the special release branch that will diverge from the original history.

```
# pyproject.toml

[tool.semantic_release.branches.main]
match = '(master|main)'
prerelease = false

[tool.semantic_release.branches."0.2.x"]
match = "0.2.x"
prerelease = false
```

This image below was the truncated git history that I generated to test your scenario.  

![Screen Shot 2024-03-16 at 11 21 25 AM](https://github.com/python-semantic-release/python-semantic-release/assets/17354856/1d8c77e9-abc0-4eaf-a794-064ca553b105)

When I execute the following command with the `0.2.x` branch checked out, I get `0.2.12` as the next version to release.

```sh
semantic-release version --print
# 0.2.12
```

**Comment by silverjam** [comment]
> > I wasn't able to find a forum for general questions, so if there's a better place to ask general support questions
> 
> This is the correct location for general support questions as of now.
> 
> > In this scenario we've created a branch from an old version of our `main` branch where the last tagged version is `0.2.11` -- so the "next" release we'd expect is `0.2.12` or `0.2.12-hotfix.1`.
> > Is there a pattern or path where we could implement our expected behavior? Thanks!
> 
> I have simulated your scenario as much as I understood and PSR will provide `0.2.12` if the configuration has `prerelease = False`. If prerelease is set to `true`, it does jump to `0.15.12` as the base version to increment from. I think latter section is a bug but I will have to apply further testing.
> 

Ok, I didn't try without prerelease so this is likely the issue.

> The configuration concept I used is documented under the Mulitbranch releases section of 

Thanks, this looks similar to https://semantic-release.gitbook.io/semantic-release/recipes/release-workflow/maintenance-releases

**Comment by codejedi365** [comment]
> Thanks, this looks similar to https://semantic-release.gitbook.io/semantic-release/recipes/release-workflow/maintenance-releases

This is not the correct documentation. The link above is for the JavaScript variant of semantic-release which is similar but not this project's docs. 

[Multibranch Releases](https://python-semantic-release.readthedocs.io/en/latest/multibranch_releases.html)

**Comment by silverjam** [comment]
> > Thanks, this looks similar to https://semantic-release.gitbook.io/semantic-release/recipes/release-workflow/maintenance-releases
> 
> This is not the correct documentation. The link above is for the JavaScript variant of semantic-release which is similar but not this project's docs.
> 
> Correct Link: [Multibranch Releases](https://python-semantic-release.readthedocs.io/en/latest/multibranch_releases.html)

Yes I realize that, apologies, I was referencing that doc as an example of what I was trying to accomplish-- the multibranch release doc is similar, but the nodejs version matched our exact use case more closely.

**Comment by codejedi365** [comment]
I haven't been able to finish the testing of this change to ensure it doesn't impact normal pre-release activity. Hopefully will get back around to this in the next few months as I am merging in some better testing of versioning.

**Comment by codejedi365** [comment]
I'm sorry, my last two months have been very busy. Not much has moved. This is still a priority and I hope to have it completed in the next few months.

**Comment by codejedi365** [comment]
Still in backlog
