### ISSUE TITLE
Update rich version dependency

### ISSUE THREAD

**Issue by sevetseh28** [python-semantic-release/python-semantic-release#888]
Hi, I'm creating this issue to raise awareness that this tool has a dependency with `rich` library that enforces version <13 
For this reason I cannot use the latest version of `rich` on my CLI project since I'm using python-semantic-release as well. It would be nice if we could update it!

Thanks

**Comment by codejedi365** [comment]
Dependabot opened PR #877 to address this, however I had been just putting it off as it requires more manual evaluation. Thanks for raising some more urgency for it, should be able to resolve soon.
