### ISSUE TITLE
GH actions docs inconsistency

### ISSUE THREAD

**Issue by rantoniuk** [python-semantic-release/python-semantic-release#907]
1. The GH Action pages are duplicated:
- https://python-semantic-release.readthedocs.io/en/latest/github-action.html
- https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/github-actions.html

3. [The action does not run `version` and `publish` per documentation](https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/github-actions.html). It runs only `version`, at least that's what I see from:
https://github.com/python-semantic-release/python-semantic-release/blob/master/action.sh#L97

(and yes, it should stay this way or it there should be a flag to disable publishing for non PyPi builds).

**Comment by rantoniuk** [comment]
Happy to help via a PR if needed.

**Comment by codejedi365** [comment]
@rantoniuk 

> 1. The GH Action pages are duplicated:
> 
> * https://python-semantic-release.readthedocs.io/en/latest/github-action.html
> * https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/github-actions.html
> 

As the pages both address GitHub actions, they do not cover the same material (so its not an easy delete of one) and I agree that it is confusing that it is not all in one. If you would be willing to consolidate the two contents into one via PR that would always be helpful.  If you decide to make a PR, please consolidate the docs into the page under `automatic-releases` and delete the top level one.  I have been meaning to get around to a doc refactor to include other VCS systems like GitLab & Bitbucket examples which will also go under `automatic-releases`. Your help is appreciated.

> 3. [The action does not run `version` and `publish` per documentation](https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/github-actions.html). It runs only `version`, at least that's what I see from:
>    https://github.com/python-semantic-release/python-semantic-release/blob/master/action.sh#L97
> 
> (and yes, it should stay this way or it there should be a flag to disable publishing for non PyPi builds).

This seems to be a remanent from prior to `v8` release. Yes, this action should not perform publish but instead users should use our publish specific action, [upload-to-gh-release](https://github.com/python-semantic-release/upload-to-gh-release), after handling their own upload to PyPi-like registry.  The example of this workflow is listed on the upload action's Readme.

Thank you for helping improve the Python Semantic Release project & documentation!

**Comment by codejedi365** [comment]
Requires update to adjustments made in #1004
