### ISSUE TITLE
Remove commit types from subjects in CHANGELOG 

### ISSUE THREAD

**Issue by paduszyk** [python-semantic-release/python-semantic-release#924]
## Description

Hey ✋🏻 First of all, thanks for such a great project! 💚

Changelog summarizes changes grouped by types - in the case of the Angular scheme, the type is simply the semantic prefix of the message: `ci`, `chore`, `feat`, etc. Within the given type, all the commits are listed with the prefix repeated, like that:

```markdown
> ### Fix
> * fix: resolve hofix 
> * fix: fix another bug
```
so, the prefix is repeated for each commit. I think that removing commit types (and capitalizing the subject) would result in a cleaner CHANGELOG:

```markdown
> ### Fix
> * Resolve hofix
> * Fix another bug
```

## Use cases

Removing prefixes will reduce redundancy.

## Possible implementation

This issue is to share my idea. I don't know how to implement it, I haven't dug into the codebase yet...

**Comment by codejedi365** [comment]
@paduszyk Thanks for the report, I am working this effort it's just taken me some time to make it public in lieu of other priorities. There is a milestone for improved changelogs that I'm consolidating all of them. Feel free to check out what is planned and add what you would like to see as well.

**Comment by codejedi365** [comment]
@paduszyk, one thing I forgot to mention is that if you wanted to see this resolved in your own projects today, you can easily define your own custom changelog template and apply it to your projects.

**Comment by codejedi365** [comment]
Still on the backlog, these changes were put on hold while I attended to other improvements and fixes
