### ISSUE TITLE
Changelog Testing fails when run across midnight

### ISSUE THREAD

**Issue by a-detiste** [python-semantic-release/python-semantic-release#991]
https://buildd.debian.org/status/fetch.php?pkg=python-semantic-release&arch=all&ver=9.8.5-1&stamp=1721692903&raw=0

tests/const.py:TODAY_DATE_STR = datetime.now().strftime("%Y-%m-%d")

sbuild (Debian sbuild) 0.85.10~bpo12+1 (04 June 2024) on x86-grnet-02.debian.org

+==============================================================================+
| python-semantic-release 9.8.5-1 (amd64)      Mon, 22 Jul 2024 23:57:22 +0000 |
+==============================================================================+

>       assert expected_content == actual_content
E       AssertionError: assert '# v1.1.0-alp...030303030))\n' == '# v1.1.0-alp...030303030))\n'
E         
E         Skipping 139 identical trailing characters in diff, use -v to show
E         - # v1.1.0-alpha.3 (2024-07-23)
E         ?                            ^
E         + # v1.1.0-alpha.3 (2024-07-22)
E         ?                            ^
E           ## Fix

FAILED tests/unit/semantic_release/changelog/test_default_changelog.py::test_default_changelog_template[Github]
FAILED tests/unit/semantic_release/changelog/test_default_changelog.py::test_default_changelog_template[Gitlab]
FAILED tests/unit/semantic_release/changelog/test_default_changelog.py::test_default_changelog_template[Gitea]
FAILED tests/unit/semantic_release/changelog/test_default_changelog.py::test_default_changelog_template[Bitbucket]
FAILED tests/unit/semantic_release/changelog/test_default_changelog.py::test_default_changelog_template_w_unreleased_changes[Github]
FAILED tests/unit/semantic_release/changelog/test_default_changelog.py::test_default_changelog_template_w_unreleased_changes[Gitlab]
FAILED tests/unit/semantic_release/changelog/test_default_changelog.py::test_default_changelog_template_w_unreleased_changes[Gitea]
FAILED tests/unit/semantic_release/changelog/test_default_changelog.py::test_default_changelog_template_w_unreleased_changes[Bitbucket]
FAILED tests/unit/semantic_release/changelog/test_release_notes.py::test_default_release_notes_template[Github]
FAILED tests/unit/semantic_release/changelog/test_release_notes.py::test_default_release_notes_template[Gitlab]
FAILED tests/unit/semantic_release/changelog/test_release_notes.py::test_default_release_notes_template[Gitea]
FAILED tests/unit/semantic_release/changelog/test_release_notes.py::test_default_release_notes_template[Bitbucket]

**Comment by codejedi365** [comment]
I have changed the title because this bug is related to changelog testing not the actual build of python-semantic-release.  The changelog testing relies upon the host system's git executable and to the system time for commit times when running through repo scenarios. The only real way to fix this is to not use a constant for the date and recalculate the date every time.

**Comment by codejedi365** [comment]
Should be able to wrap in the resolution with this testing refactor I'm accomplishing this week
